### ISSUE TITLE
[BUG] Opening a project that never loads will put it into a forever "Bring to Front" state

### ISSUE THREAD

**Issue by orels1** [vrchat-community/creator-companion#101]
**Describe the bug**
If you open a project and it crashes on load or you simply terminate the process - VCC will forever have it marked as "Open in Unity" and not show the "Open Project" button anymore until the refresh/restart of the VCC.

**To Reproduce**
1. Open any project that has an SDK version >= 3.1.11
2. Kill the unity process
3. Observe the green dot and "Bring to Front" buttons

**Expected behavior**
The projects should be put into an "Opening..." state until the project actually opens and connects to the VCC, with some timeout in case of crashed / terminated processes.

**Additional Notes**

Bring to front button should also probably be a bit more special, so it doesn't fade into the background as much as it does now (a border color or some other highlight might be worth it)

**Comment by DrBlackRat** [comment]
I think it would look good, if the light blue "Open Project" button would turn into a light or lime green "Bring To Front" button. The font color should probably stay white in that case as well.

**Comment by orels1** [comment]
This has been addressed for the next closed beta. Here are some previews of the solution:

**Idle State**
![image](https://user-images.githubusercontent.com/3798928/222538283-55ca898c-2c55-47b7-b3c2-f5d87c0a5597.png)

**Opening State**
![image](https://user-images.githubusercontent.com/3798928/222538323-99190a88-f2e1-4f42-b97c-cbeb98641c54.png)

![image](https://user-images.githubusercontent.com/3798928/222538419-043d2358-b749-4cbf-9a2a-de3ff58db2c5.png)

**Open State**
![image](https://user-images.githubusercontent.com/3798928/222538634-844b07fe-f6f0-4e50-9f75-8f0a7ad43fff.png)

This extends to other views / pages where the project/open button is visible.
This change also improves the button layout a bit
