### ISSUE TITLE
[BUG] VCC Identifies and uses Unity `2019.4.30f1` instead of `2019.4.31f1` when both are installed

### ISSUE THREAD

**Issue by rrazgriz** [vrchat-community/creator-companion#103]
**Describe the bug**
I installed `Creator Companion Web Closed Beta 2.0.0-cb.3` and it detected my Unity install (I don't recall if it specified the version). I migrated a project to VCC, but upon opening it, it was `2019.4.30f1` instead of the correct `2019.4.31f1`.

**To Reproduce**
Unsure exactly - I have two installs of Unity 2019, `2019.4.30f1` and `2019.4.31f1`.

**Expected behavior**
VCC should always default to `2019.4.31f1` when available, or whatever the correct version is.

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Update: 22H2 (KB5022834)

**Additional context**
The dropdown does identify both versions, and I was able to select and use the correct version easily.

**Comment by orels1** [comment]
Fixed in latest closed beta
