### ISSUE TITLE
[BUG] [VCC-WEB] Bring To Front button not correctly working and throwing errors  

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#105]
**Issue:**  
With the old Unity based VCC the `Bring To Front` would always bring the Unity window to the front, no matter what, even if there was just another window in front of it.
This is not case with the cb4 version of the WEB UI based VCC, there the `Bring To Front` button only brings the project to the front when it was minimized before.
But even then, for some reason it still throws an error in the console.

**Suggestion / Expected Behaviour:**
- The `Bring To Front` button should always bring the project to the front, even if there is just another window on top of it  
- It should not throw an error when just normally pressing the button when it actually worked  

**Attachments:**  
Here is a picture showcasing the error in the log:
![image](https://user-images.githubusercontent.com/46327609/222901329-8b2d9487-5282-417a-a503-24e822983551.png)

**Comment by orels1** [comment]
This should be addressed in the VCC 2.0!
[Grab it from here](https://vrchat.com/download/vcc)
