### ISSUE TITLE
VCC won’t let me update to a new unity

### ISSUE THREAD

**Issue by AcePandora** [vrchat-community/creator-companion#108]
![2D7F083D-91E4-4578-B187-81F75F303C5D](https://user-images.githubusercontent.com/127035677/222967397-95f32a1a-6008-43c7-a569-82bf3813e6b1.jpeg)
Everytime I open up my creator companion or reinstall it always shows that I need a requirement. It doesn’t show me a unity version to install and won’t let me press any of the buttons on the screen. I have tried installing different versions of unity except by the VCC but it won’t work.

**Comment by orels1** [comment]
This should be addressed in the VCC 2.0!
[Grab it from here](https://vrchat.com/download/vcc)
