### ISSUE TITLE
[BUG] Leaving and returning to the Project Management screen does not indicate a package is still downloading.

### ISSUE THREAD

**Issue by Vowgan** [vrchat-community/creator-companion#109]
**Describe the bug**
When updating a package to the newest version, if you leave the Manage Packages page for that project and come back, it will simply show you those packages missing until the download is complete. If this goes on for an extended amount of time, the user may think they need to install them again and run into possible problems.

**To Reproduce**
1. Press Update on a package in your project in VCC 2 b4
2. Before the update is complete, change screens and come back to this one. (I used the Logs screen)
3. If the package is not done downloading, it will display that package as not being installed at all.

**Expected behavior**
Loading into this page should know whether or not a package is being downloaded, and show the update in progress visuals. It may be possible to lock certain player inputs while an update is happening, such as not being able to click update on a different package until the currently updating ones are complete.

**Screenshots**
Here, the "VRChat SDK - Worlds" package is being updated, but since I have left and come back, it displays as empty.
![image](https://user-images.githubusercontent.com/47050502/223497734-ff1e78f2-276b-40bc-b1bb-cbdbf73c8730.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Additional context**
Very, very slow download speeds are likely the only time this may even appear as an issue. However, today this update took roughly two minutes for unknown reasons, which may or may not be indicative of a different bug at play as well.

**Comment by orels1** [comment]
Fixed in latest closed beta. Now locks all interaction with the list and doesn't forget the loading state if navigated back and forth
