### ISSUE TITLE
[BUG] Stuck on "requirement" screen after installation

### ISSUE THREAD

**Issue by Panrium** [vrchat-community/creator-companion#110]
**Describe the bug**
When I install VCC and run for the first time, I found I cant interact with the upcoming requirement screen, with the Unity editor version invisible. I looked it up on the VCC docs and was told to delete the repos folder in C:\Users\Username\AppData\Local\VRChatCreatorCompanion\. 

After closing VCC, deleting repos and restart VCC, the repos folder didn't regenerate as expected and VCC is stuck as before.

**To Reproduce**
1. download VCC installer and installed in disk D
2. run for the first time, stuck in "requirements"
3. VCC docs told me to close VCC, delete repos folder, restart VCC and repos would be recreated thus solving the problem.
4. When I restart VCC the repos folder didn't show up and it doesn't change the status quo

The link to the resolution I looked up : https://vcc.docs.vrchat.com/guides/faq/#what-do-i-do-if-im-stuck-on-the-requirements-screen

**Screenshots**

![image](https://user-images.githubusercontent.com/127253613/223553296-d00512d4-85b6-4145-a5a3-acdb715a31a3.png)

**Desktop *
 - OS: Windows 10 pro
 - Version: 21H2

**Additional context**
I had vrchat compatible version of unity installed previously with unity hub

**Comment by Panrium** [comment]
![image](https://user-images.githubusercontent.com/127253613/223555419-78934beb-37bb-4ea8-b8f1-79cb9ae453ce.png)

screenshot of the solution I followed in VCC docs

**Comment by orels1** [comment]
This should be addressed in the VCC 2.0!
[Grab it from here](https://vrchat.com/download/vcc)
