### ISSUE TITLE
[BUG] VCC become extremely slow with one or more user repos.

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#112]
**Describe the bug**
VCC become extremely slow with one or more user repos.

**To Reproduce**
1. Close VCC (to avoid another issue #111)
2. add userRepo(s) in settings.json in some way (you may edit settings.json or use vpm cli)
3. Open VCC
4. Select project
5. It freezes for few seconds

**Expected behavior**
No freeze

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Version 10.0.22621 N/A Build 22621

My friend says this also happens on windows 10

**Additional context**

**Comment by orels1** [comment]
This should be addressed in the VCC 2.0!
[Grab it from here](https://vrchat.com/download/vcc)

**Comment by ni1chigo2115** [comment]
The freeze between reads is gone, but now the user repos itself is not loaded.
![vrrhtml5](https://user-images.githubusercontent.com/23652237/224198611-0350a740-8523-4c33-966d-72892c44de13.png)
I have waited for more than 10 minutes, but the list has not appeared at all.
Perhaps even if I wait for an hour, it will not appear.
