### ISSUE TITLE
[BUG] [VCC-WEB] At specific window sizes the buttons on the Projects page start to lose alignment in List View

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#114]
**Issue:**  
When you set the window of the Projects page of the VCC to a specific size the Project Type, Open Project and Manage Project buttons start to get misaligned for Projects who's path is to long to be fully displayed.

This is relatively hard to reproduce but I've listed the easiest way to get it to happen below:
1. Open the VCC, go to the Projects page and set it to be in List View
2. Change the window height to a size so that a scroll bar appears on the right side  
3. Slowly start make the width of the window smaller until the path of a projects starts to get cut

If you do this you *should* notice the problem.

**Expected Behaviour:**
The buttons should stay in alignment no matter what.

**Attachments:**  
Here is a picture showcasing the issue:
![grafik](https://user-images.githubusercontent.com/46327609/224076844-06df37ba-3cfc-4cad-852c-d1b327208fa1.png)

**Comment by orels1** [comment]
Seems like we cut the max length of the path a bit too close to the limit. Adjusting that seems to address the issue.

**Comment by orels1** [comment]
Fixed in v2.0.1
