### ISSUE TITLE
[BUG] [VCC-WEB] Window Size is forgotten after Quitting/Relaunching Creator Companion

### ISSUE THREAD

**Issue by BluWizard10** [vrchat-community/creator-companion#117]
**Describe the bug**
In a nutshell, resizing the Window from the edges will not be remembered to what the window was resized to upon quitting and relaunching Creator Companion.

**To Reproduce**
1. Open the App.
2. Resize the Window from the corners of the App to whichever size you're comfortable with.
3. Close Creator Companion.
4. Re-open Creator Companion.

**Expected Behavior**
The size of the Window should be remembered upon relaunching Creator Companion.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 22H2

**Additional Context**
The default size is TOO DAMN SMALL on a 4K monitor!

**Comment by Faxmashine** [comment]
Confirmed for 2.0.3

**Comment by BluWizard10** [comment]
Seems to me this is no longer an issue! As of Creator Companion v2.2.0 and newer, the Window Size is correctly remembered now each time the app is closed or re-opened!
