### ISSUE TITLE
[BUG] VCC 2.0 cannot set the path to Unity editor

### ISSUE THREAD

**Issue by Panrium** [vrchat-community/creator-companion#121]
**Describe the bug**
It shows "Cannot read empty file from "C:\Users\Administrator\AppData\Local\VRChatCreatorCompanion\settings.json" each time I wanted to set a path for unity editor

**To Reproduce**

1. In the project panel, it says "Path to a Unity Editor is not set, you will be unable to open projects."
2. Click on 'fix now', it displays
![image](https://user-images.githubusercontent.com/127253613/224213951-a293a1ad-39e3-41bf-822d-81bc95972baf.png)

3. Selected "I already have Unity", and set the correct path to my editor, which was D:\2019.4.31f1\Editor\unity.exe

4. an error notification came up:
Cannot read empty file from "C:\Users\Administrator\AppData\Local\VRChatCreatorCompanion\settings.json"
![image](https://user-images.githubusercontent.com/127253613/224214207-c8b22845-f6e7-4ba4-9745-37d72405b07a.png)

then the program freezes.

5. I went to look for the settings.json file, found out that it is a 0kb file and it shows nothing when I open it with notepad.
![image](https://user-images.githubusercontent.com/127253613/224214993-84fd1b85-9fe1-4311-bfae-9d2b9cf34b15.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 21H2

**Additional context**
I've met similar problem with version 1.6 previously, dunno if it helps

**Comment by momo-the-monster** [comment]
We will create a new Settings file if the current one is empty.

**Comment by orels1** [comment]
Something else worth exploring: if the file fails to deserialize (reported by testers), like if some values became null that shouldn't be null, we should maybe open a little window like:

> Settings file appears to be corrupted, VCC can make a fresh settings file so it can launch correctly. The current settings will be saved as `settings-old.json`

With 2 buttons: "Create New Settings" and "Close VCC" to back off.

That way users can at least natively reinitialize and then submit the broken settings file to us / manually inspect it

**Comment by orels1** [comment]
VCC now automatically clears and re-creates 0-byte settings files and also provides a special experience for settings files that contain malformed json



![Image](https://user-images.githubusercontent.com/3798928/233641679-2e1f2054-0cb3-4b52-b883-2662e255a25f.png)
