### ISSUE TITLE
[BUG] Packages list for project stays in Loading state forever intermittently

### ISSUE THREAD

**Issue by jjnuccio** [vrchat-community/creator-companion#126]
**Describe the bug**
Loading spinner stays forever on selected Project page while resolving packages 

**To Reproduce**
- Go to Projects -> select project
- package resolution stays in Loading state forever, with spinner and package dropdowns greyed out (waited 10+ minutes)
- ****  this possibly only happens under high network usage **** 
- Only resolved after closing/opening VCC several times 

**Expected behavior**
- packages resolve after a few seconds, or Error message explaining what's going on 

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 2.0.0

**Comment by orels1** [comment]
This should've been addressed in version 2.0.1+
