### ISSUE TITLE
[VCC2] List of bugs, missing features, and design flaws

### ISSUE THREAD

**Issue by foxscore** [vrchat-community/creator-companion#128]
I know this is a long post with widely differing themes, but it's difficult for me to separate them into their own little posts.

---

- “User repositories” are still cached with a random ID instead of a hash, making the cache useless and impacting long-term performance

- The background-animation on “add/remove package” buttons is too slow when compared to the background of the row. This leads to what looks like (and kind of is) a visual glitch when hovering from one button to the next (vertically)

- The first-time-introduction shows a bunch of buttons *(the ones with images)* that don't work

- The log page doesn't show any entries from before the UI was loaded

- The log page doesn't print nearly enough information to debug anything

- All log messages are shown as notifications; will cause problems when the issue above gets resolved

- The type of entry in the log page is not colored. Should be: (red=error, yellow=warning, white=information, gray=debug), but is: (any=white)

- User repositories are still not configurable in the settings page

- The tools page is static (it should load other available tools from the Tools directory)

- The dropdown, of the “Create New Project” / “Open Project” button, is too close to the button; put more spacing in between the two

- No option to show more details *(or even the package.json)* in the package list

- Packages from user repositories are always listed under “Community”, regardless of the repositories name

- Attempting to remove dependencies cancels the operation, instead of telling the user “The following packages will also be removed” (or something along those lines) and asking them if they want to remove them as well or cancel the operation. This WILL lead to irremovable packages, just by two packages depending on each other.

- There is no “Restore Backup” option

- Search bar does not respect keywords, description, author, or any other important identifiers _(not including the package name)_

- Refreshing the “Manage Packages” list when having user repositories, will cause errors. VCC does not release the write-lock on cache files, and does not allow “other processes” *(which includes itself)* to read it.

- The “settings.json” button does not actually open the file, only the folder it's contained in. This may be intended behavior, but it seems weird, so I'll still make a note of it.

**Comment by Faxmashine** [comment]
Thank you for the feedback! I tried to respond to each of your requests below.
Please understand that we can't complete issues that contain more than a single request, though feel free to submit individual issues. (Unless we've already addressed them!😄)

> - “User repositories” are still cached with a random ID instead of a hash, making the cache useless and impacting long-term performance

> - User repositories are still not configurable in the settings page

> - Packages from user repositories are always listed under “Community”, regardless of the repositories name

> - Refreshing the “Manage Packages” list when having user repositories, will cause errors. VCC does not release the write-lock on cache files, and does not allow “other processes” *(which includes itself)* to read it.

We're looking into those!

> - The background-animation on “add/remove package” buttons is too slow when compared to the background of the row. This leads to what looks like (and kind of is) a visual glitch when hovering from one button to the next (vertically)

I'm having trouble replicating this behaviour - can you please elaborate?

> - The first-time-introduction shows a bunch of buttons *(the ones with images)* that don't work
That's fair enough! We considered showing those buttons at the end of the introduction, allowing users to go straight to those tabs. We may end up changing the onboarding flow in the long term.

> - The log page doesn't show any entries from before the UI was loaded

> - The log page doesn't print nearly enough information to debug anything
We've added additional logging in the 2.0 release. The logs file also includes some extra information. Is there a particular aspect of the VCC you'd like to see more logging for?

> - All log messages are shown as notifications; will cause problems when the issue above gets resolved

> - The type of entry in the log page is not colored. Should be: (red=error, yellow=warning, white=information, gray=debug), but is: (any=white)

That's issue https://github.com/vrchat-community/creator-companion/issues/127

- The tools page is static (it should load other available tools from the Tools directory)

Hmm, that's an interesting idea. Though we may want to wait until we have more tools worth showing off! 😉

> - The dropdown, of the “Create New Project” / “Open Project” button, is too close to the button; put more spacing in between the two

Great suggestion!

> - No option to show more details *(or even the package.json)* in the package list

If you hover over a package, you'll see a tooltip with additional information.

> - Attempting to remove dependencies cancels the operation, instead of telling the user “The following packages will also be removed” (or something along those lines) and asking them if they want to remove them as well or cancel the operation. This WILL lead to irremovable packages, just by two packages depending on each other.

We have a few issues related to that. (But not *exactly*.) https://github.com/vrchat-community/creator-companion/issues/17 https://github.com/vrchat-community/creator-companion/issues/10

> - There is no “Restore Backup” option
> - Search bar does not respect keywords, description, author, or any other important identifiers _(not including the package name)_

Those are great ideas!

- The “settings.json” button does not actually open the file, only the folder it's contained in. This may be intended behavior, but it seems weird, so I'll still make a note of it.

Some users were having issues when the VCC tried to open it directly, so we intentionally changed it to open the folder instead.
