### ISSUE TITLE
[BUG] Latest version is not based on semver.

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#129]
**Describe the bug**

**To Reproduce**
1. Add `https://vpm.nadena.dev/vpm.json` as user repo
2. See latest version of Modular Avatar.

**Expected behavior**
Latest version should show latest version based on SemVer.

**Actual behavior**
Latest version show last version on vpm repo json.

**Screenshots**
<img width="818" alt="image" src="https://user-images.githubusercontent.com/22656849/224470778-7276a015-b389-4e00-8fa4-3f288edc8f89.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.0.0-2.0.1

**Additional context**
Because official repo is ordered by version ascending so this problem doesn't happens.
However, vrchat-community/package-list-action (used by `https://vrchat-community.github.io/template-package-listing/index.json`) creates json ordered by version descending so this problem happens.
<img width="910" alt="image" src="https://user-images.githubusercontent.com/22656849/224471694-c385ef21-b377-4bcb-bb99-0dd0770436d8.png">

**Comment by kurotu** [comment]
Related problem: Versions dropdown is not sorted by semver. Probably the list uses same order of `versions` from json as is.

VRCQuestTools (https://kurotu.github.io/VRCQuestTools/index.json)
![image](https://user-images.githubusercontent.com/74851548/224481869-71c9ff0f-2da7-4582-97aa-2a7a83100f29.png)

Package Resolver Tool:
![image](https://user-images.githubusercontent.com/74851548/224482145-5e4bbdab-ba41-44b4-ad1d-e100adaa6a46.png)

**Comment by orels1** [comment]
2.0.1 introduced the fix for the package version sorting specifically
![image](https://user-images.githubusercontent.com/3798928/224495408-fad15110-ee62-4ba8-be80-97720fe68430.png)

Are you sure you can replicate the issue in the 2.0.1?

**Comment by orels1** [comment]
This is addressed internally as a part of Community Listings support work

**Comment by anatawa12** [comment]
Recent changes to official repository (migration to GitHub pages) make official repository affected by this problem. (with VCC 2.0.4) I found VRCSDK 3.1.12 by reading vrc-official.json however I think most users cannot find VRCSDK 3.1.12.

**Comment by orels1** [comment]
This has been fixed as a part of 2.1.0
