### ISSUE TITLE
[BUG}

### ISSUE THREAD

**Issue by Ashlen-Creates** [vrchat-community/creator-companion#13]
**Describe the bug**
So i click on options but nothing works

**To Reproduce**
It may just be me but i need help..

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by momo-the-monster** [comment]
Can you provide any more information about the issue, or logs? I assume you mean "Settings", since there is not an "options" screen.

**Comment by momo-the-monster** [comment]
Closing due to lack of follow-up information, please reopen if you can provide additional details, thanks!
