### ISSUE TITLE
Build & Publish for Windows

### ISSUE THREAD

**Issue by doverchat** [vrchat-community/creator-companion#130]
I am a first time user.  I have made it all the way to this Build and Publish for Windows and can not get past this step.  What am I doing wrong?  Please help. 
![Screenshot (769)](https://user-images.githubusercontent.com/127513984/224474881-d58a8b60-f2ec-4367-bb87-6ac7803786bb.png)

**Comment by doverchat** [comment]
I tried to delete all the imported files and start over.  and i was able to access the build and publish button. but now i have all these...errors??  alerts??  like 30 of them?   what do i do???

**Comment by anatawa12** [comment]
Can you show me the error messages? Please make sure you've installed & using correct version of Unity and has Windows build support

**Comment by BluWizard10** [comment]
This is a common glitch with the VRChat SDK. Close the Control Panel, then go to to the Menu Bar in Unity and click `VRChat SDK -> Reload SDK`

This should instantly fix your issue.

**Comment by BluWizard10** [comment]
This is a common glitch with the VRChat SDK. In order to upload an Avatar, you MUST disable the Avatars that are not being used and leave only 1 to be viewable in the Scene.

Reopen the Control Panel after doing that and NOW you should be able to upload.

**Comment by doverchat** [comment]
> Can you show me the error messages? Please make sure you've installed & using correct version of Unity and has Windows build support


see the bottom left of the screen shot... there is a lot of those with the white bubble and the red  !  i dont know if these mean anything or not. 
![Screenshot (771)](https://user-images.githubusercontent.com/127513984/224556335-398b5d61-4034-4c62-9afd-09b624ed57fb.png)

**Comment by Faxmashine** [comment]
I hope you've been able to resolve your issue! If you still require assistance, please visit our official Discord or contact our support team at help.vrchat.com.
