### ISSUE TITLE
Backup Function not longer working in 2.X [BUG]

### ISSUE THREAD

**Issue by Gammelstulle** [vrchat-community/creator-companion#131]
**Describe the bug**
the backup function in CC no longer works ( at least as I remember). I found this out the hard way. 
The created package size or the size of the unpacked backup folder does not match the size of the source folder
If you try to use the backup nevertheless, Unity will try to build the project out of his local cache. (what takes ages and not gave me a working project folder in the end)

I'm just dump? Did I had copy over the backup to the existing projekt folder?
As this would explain the packadge size.
My Projektfolder is 2.5 ish GB in size, while the Backup is only 500 mb so there is clearly missing a lot. 

**Additional context**
I am glad that I could save my old project with a rescue tool ;_;
Imagine you are making backups that are not work like a backups. 🙈

**Comment by orels1** [comment]
The backup does not back up the library folder because it is temporary data, yes. Backing up the whole project folder (including Library) is not advised by Unity itself. It should be safe to delete, and it will be re-created when you open the project 🤔

**Comment by orels1** [comment]
I am going to close this issue due to inactivity
