### ISSUE TITLE
[BUG] Application Error on launch when another instance is already running

### ISSUE THREAD

**Issue by sync1211** [vrchat-community/creator-companion#132]
**Describe the bug**
When starting VCC with another instance already running (e.g. on another screen), the new instance will display a Windows "Application Error" popup.

**To Reproduce**
1. Open VCC
2. Open VCC again without closing the existing instance

**Expected behavior**
The new instance doesn't crash.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/17365446/224494119-f5507784-2f11-4ab1-9089-605f7e36b1ca.png)
`The exception "Unknown Error" (0xe0434352) occurred in the application at location 0x00007FFA836DCD29`

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (22H2, Build 19045)
 - Version v2.0.1

**Additional context**

**Comment by orels1** [comment]
Running two instances of the VCC is not supported. There are no plans to support that at this time.

**Comment by sync1211** [comment]
I know. However it shouldn't cause an exception when another instance is launched.

**Comment by sync1211** [comment]
The exception is no longer thrown in v2.1.0, so I'll mark this as closed.
