### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KeresNecronym** [vrchat-community/creator-companion#136]
My projects aren't loading, like at all, I check the logs but they all look normal
the log just says "Opening project: C:\Users\bread\AppData\Local\VRChatProjects\Sofie" and unity hasn't loaded at all
everything is updated and I've restarted my computer several time and nothings worked. I have uninstalled and reinstalled everything as well and still nothing.

Normally I would see the unity project with the VRCSDK and such but not even Unity loaded.

This issue has been going on for about 4 months now and nothings worked, I also asked Unity directly thinking it was a Unity issue but they also didn't help much.

**Comment by clienthax** [comment]
Are you able to launch unity via the unity hub itself?

**Comment by Faxmashine** [comment]
Please let us know if you have any additional information! You may want to try one of our template repositories, and opening then via Unity Hub directly.
