### ISSUE TITLE
[FEATURE] Allow legacy local package support (hear me out)

### ISSUE THREAD

**Issue by IlexisTheMadcat** [vrchat-community/creator-companion#14]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to convert `.unitypackage` to local packages, however not all work as well as they did in an Assets folder.
We all use packages in the form of `.unitypackage`, however it becomes tedious to keep them organized in multiple projects, whether they be worlds or avatars. The main issue here is not all were built with VCC in mind, most just work coincidentally. 
I've noticed that both of two popular shaders (lilToon and Poiyomi 8.1) have broken custom UIs. Some scripts don't register for some reason, including Gesture Manager (figured below) and Alpha Blend Interactive's CCK.

**Describe the solution you'd like**
Allow VRCSDK Package Maker and/or VCC to create a folder in the Assets root directory to place packages in for compatibility.
💡Idea: Create a new tick box in the local Package Manager to enable Compatibility Mode for _that_ package. Add an optional VPM parameter in the package's `.json` called `isVpmCompatibilityMode`. Both have been figured below (no modifications have been made, these are just for demonstration). If VCC finds that this parameter is present in the `.json`, create a new folder at `{project}/Assets` (configurable per project?) called `VCC Packages` if it doesn't already exist.
I have faith in the potential of this tool for even more than just VRChat, I believe it can help with many other projects. I beg of this to work, I've heard of other users complain about the need to have package authors convert stuff, and half of us don't even know C#.

**Describe alternatives you've considered**
Well currently the only workaround is to import packages as `.unitypackage`, having missed out on the versatility of the plug-and-play features VCC provides across multiple projects.
As for the above solution, you could instead rely solely on VCC and add the aforementioned tick box to the packages list entry if that package has `isVpmCompatibilityMode` in its `.json`.

**Additional context**
![image](https://user-images.githubusercontent.com/50256109/200157228-ed8fcc20-f265-44d1-8807-dd4230aa6940.png)
![image](https://user-images.githubusercontent.com/50256109/200157332-379813dd-acca-46ed-b177-a85982b0f749.png)
![image](https://user-images.githubusercontent.com/50256109/200157831-9bf6e783-ac1c-4848-a8c2-01cb3afd6f83.png)
GestureManager3.7 is a product of `BlackStartx#6593` (Discord).

**Comment by IlexisTheMadcat** [comment]
Yes, I did test GestureManager3.7 as a package and as an asset. One at a time of course, only the one in the Assets folder worked/loaded correctly.

**Comment by momo-the-monster** [comment]
You can create your own [Project Templates](https://vcc.docs.vrchat.com/vpm/templates) to easily reuse .unitypackages across your projects - I believe it provides all the functionality you've described above without needing "compatibility mode".
