### ISSUE TITLE
[BUG] Project hierarchy and scene gets wiped after an legacy avatar migration

### ISSUE THREAD

**Issue by TW1STaL1CKY** [vrchat-community/creator-companion#141]
**Describe the bug**
After migrating my legacy SDK3 avatar project (to a copy) and opening the project, I find that the hierarchy has been wiped, replaced with the default "Untitled" scene containing a light and a camera.
Everything else in the project is fine, just what I had set up in the hierarchy is gone.

**To reproduce**
1. Go to the Projects tab in the creator companion and find a legacy avatar that needs migrating
2. Choose Migrate a Copy, then Yes Migrate now
3. Once it's done, load the project
4. While loading, it will show it's importing everything that was in the old project (not sure if that's normal). Once that's done, Unity will open with all the expected files in the Resources, but everything in the Hierarchy will be "reset"

**Expected behavior**
To have the project's hierarchy intact after the migration.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 22] 10.0.19045 Build 19045

**Additional context**
_**I found a workaround to the problem.**_ My project's scene is saved in a .unity file which I had stored in the /Assets/Scenes folder - I was able to drag the file into the hierarchy and everything was back the way it was intact.

I assume it already does this in some form, but would it be possible for VCC to detect if the migrated project has a blank hierarchy and automatically add .unity scenes found in the Assets folder back to the hierarchy? If multiple .unity scenes are found, it could ask the user which ones to add back?

**Comment by anatawa12** [comment]
I think this is not a bug.
Unity just opens empty scene if last-opened scene information is not found. 
We can create and use multiple scenes (at Assets/Create/Scene on menu bar).

**Comment by TW1STaL1CKY** [comment]
If nothing can be done on VCC's side, please can we at least get a warning that scenes may be missing from the hierarchy after migration and the user would need to drag them back in?

I've noticed other people having this happen as well, so giving a message telling them what to do will help them immensely. 😄

**Comment by anatawa12** [comment]
It is general knowledge to open file just that double clicking existing scene, isn't it? OR most doesn't know how to open / create scenes?

**Comment by Sayamame-beans** [comment]
Unfortunately, I suspect that many people are not even properly aware of the existence of Scene. (I don't know how it actually is.)
I don't think there is much overlap between the demographic that knows the Unity specs and operations and the demographic that is modifying avatars in VRC. It's probably not a good thing, but I don't think it's unnatural.

That said, the experience would be better if the last Scene that was opened before the migration could be opened automatically.

**Comment by Faxmashine** [comment]
Thanks for raising this issue! We added an item to our FAQ last year to help users understand what's going on.

https://vcc.docs.vrchat.com/guides/faq#where-did-my-scene-go-why-is-it-blank

... But they might not know that if they don't read our FAQ! And novices might not have the necessary Unity knowledge to know how scenes work.

If you'd like us to add this feature to the Creator Companion, please create a new post. That'll make it easier for us to judge how important the issue is, and it'll make it easier to find for users experiencing the same issue.
