### ISSUE TITLE
[FEATURE] Please consolidate local packages with the same name into the same grouping with the version dropdown

### ISSUE THREAD

**Issue by techanon** [vrchat-community/creator-companion#16]
**Is your feature request related to a problem? Please describe.**
I have two different versions with the same package name. When I add the two different versions to the VCC local packages under Settings, it lists them independently of each other.

**Describe the solution you'd like**
I would expect that if I add multiple versions of the same package name that the versions would be consolidated into the same entry with the different version numbers in the dropdown.  
For any fields that aren't the same (such as the package description changed between versions), the latest version should be used for that display information.

**Describe alternatives you've considered**
No alternatives, is just an improvement.

**Additional context**
What it looks like currently:
![image](https://user-images.githubusercontent.com/1837484/200198470-5375a390-8ce9-4072-8809-f669ec62a9db.png)

**Comment by momo-the-monster** [comment]
This is already the case. Are you possibly using different names in your package manifests?
![image](https://user-images.githubusercontent.com/737888/200962325-4c39f2dd-5e10-4ce3-b801-4414eaf5d112.png)

**Comment by techanon** [comment]
An oversight on my part, apologies. I did update a portion of the name between version I had forgotten about. Thank you.
