### ISSUE TITLE
[BUG} Heirarchy Cleared - Project Migrates Without Objects

### ISSUE THREAD

**Issue by mariomguy** [vrchat-community/creator-companion#18]
**Describe the bug**
Migrating a copy of my project cleared the hierarchy. The entire world needs to be rebuilt from scratch.

**To Reproduce**
1: Migrate
2: Open

**Expected behavior**
Project appears with all objects and appropriate hierarchy.

**Screenshots**
Just imagine the hierarchy with only a camera and directional light, and nothing else.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version [e.g. 22] Build 19045

**Additional context**
Some packages were included in the project, including CyanEmu, which emulated VRC for play-in-editor.

**Comment by momo-the-monster** [comment]
You'll need to provide some more information - our test projects all migrate correctly. Did you reopen the target scene after migration?

**Comment by momo-the-monster** [comment]
Closing due to lack of follow-up information, please reopen if you can provide additional details, thanks!
