### ISSUE TITLE
[FEATURE] Compact project view with sort functionality.

### ISSUE THREAD

**Issue by AbsentQuarter** [vrchat-community/creator-companion#19]
## Compact Project View List
Please consider a compact view for projects with the option to sort by name, dates, directory, project type (world / avatar), exct~ 
The current unity hub (example below) would be a great example to use when designing. 

![image](https://user-images.githubusercontent.com/66880916/201260895-0dd2d809-b078-4717-943e-606e5d49be97.png)

**Comment by Faxmashine** [comment]
The newly released Creator Companion 2.0 is more compact, making it easier to browse long lists of projects.
We'd still like to implement sorting functionality. We're tracking that request separately in https://github.com/vrchat-community/creator-companion/issues/148

Thank you for your request!
