### ISSUE TITLE
Package resolver does not format long package names properly

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/creator-companion#196]
![Image](https://user-images.githubusercontent.com/61843462/225437391-536f1757-2f5b-4634-af49-5b0a55210fd4.png)
Names cut off, no option.

![Image](https://user-images.githubusercontent.com/61843462/225437400-a33265b6-ff12-46d9-bbb3-2474441e7765.png)
Options visible, but names are still cut off.

![Image](https://user-images.githubusercontent.com/61843462/225437423-634d4a4e-8b02-42d9-997f-87b919f8c338.png)
 Names visible, but buttons are no longer formatted properly.

**Comment by orels1** [comment]
This has been fixed with VPM Resolver 0.1.28
