### ISSUE TITLE
The .gitignore of the generated project is wrong

### ISSUE THREAD

**Issue by konjacdesert** [vrchat-community/creator-companion#2]
Currently the Packages/.gitignore generated by this tool is not functioning properly.
```
/*/
!com.vrchat.core.*/
com.vrchat.*/
```
I think the second and third lines are reversed.

**Comment by momo-the-monster** [comment]
Thanks, @konjacdesert - we'll remove line 3 altogether.

**Comment by momo-the-monster** [comment]
Fixed in next release by updating the logic which checks for the expected lines.
