### ISSUE TITLE
Have Settings check Project Type when Importing

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/creator-companion#203]
The Settings class within vpm-core-lib allows you to add an SDK2 project, for example, relying on the front-end to deny them. Let's check the type using something similar to this method from the Unity app:
if (!UnityProject.ProjectTypeShouldBeAdded(type))
{
    VRCLogger.LogWarning($"Project at {folder} looks like the type {type}, which cannot be added.");
    return;

**Comment by Faxmashine** [comment]
Currently the project is simply shown as 'Unknown', correct?
(Which may or may not be an SDK2 project)

**Comment by momo-the-monster** [comment]
Yeah, I think this is actually 'will not do' now, because we found some cases where it makes sense to add an unknown project.
