### ISSUE TITLE
Add a list of installed Repositories to Settings

### ISSUE THREAD

**Issue by orels1** [vrchat-community/creator-companion#205]
- The Settings screen packages tab should have a list of all installed repos
- Each repo should be on its own row, separated by Built-In and User Repositories lists
- You should be able to toggle repo's active state with a checkmark near each one
- For user repos you should be able to see the repo url
- There should be an "Add Repo" button similar to the User Repos Add button which kicks-off addition flow
- There should a remove repo button near any of the user repos

**Comment by pema99** [comment]
:rocket:

**Comment by float3** [comment]
🚀

**Comment by orels1** [comment]
Got the basic setup going


![Image](https://user-images.githubusercontent.com/3798928/225960586-9684d13d-0828-450c-a37e-911b935cdcac.png)


Need to add separators for Built-In / User Repos as well as some details and action buttons

**Comment by orels1** [comment]
![Image](https://user-images.githubusercontent.com/3798928/225991822-5f60d35f-d869-4cf3-80a5-927fa15c2313.png)

The UI portion is almost done, but I'll need to tweak the repo data returned back to the frontend so I can display more useful information

**Comment by orels1** [comment]
Updated a lot of data flows to return something more useful than just the name + cleaned it up a bit


![Image](https://user-images.githubusercontent.com/3798928/226489322-96f19868-54bc-4758-a736-b3023c61e1ee.png)

Repos can now also supply an `id` field that will be used internally for passing the data around. Otherwise the `url` will be used as a unique identifier

**Comment by orels1** [comment]
This has been released as a part of 2.1.0
