### ISSUE TITLE
Register and handle `vcc://` url scheme

### ISSUE THREAD

**Issue by orels1** [vrchat-community/creator-companion#206]
We need to add support for interacting with VCC via the `vcc://` URL scheme.

- VCC should be reachable via the `vcc://` protocol
- `vcc://vpm/add-repo?url=<repoUrl>` should show the VCC and kick-off the User Repo addition flow

**Comment by momo-the-monster** [comment]
Progress! Got the scheme working via manual registry edits. 
![image](https://user-images.githubusercontent.com/737888/225775811-c3c1831c-8600-4ac3-9137-83b1a4616d29.png)

Now to get it set up correctly by InnoSetup.

**Comment by orels1** [comment]
This has been released as a part of 2.1.0
