### ISSUE TITLE
User Repo addition flow UI

### ISSUE THREAD

**Issue by orels1** [vrchat-community/creator-companion#208]
As a part of the User Repositories flow, we need to add a dialog for adding a new repo to the VCC.

This flow should look like this:

- When adding the repo using the `vcc://` link
  - The dialog should open automatically
  - The dialog should display the information about the repository (loaded through the backend)
  - The dialog should display the list of packages available in the repository
  - The dialog should display a disclaimer with a consent button to download custom repo contents
- When adding the repo manually
  - There should be an initial dialog with an input field to paste the repo URL into
  - After pasting the URL - it should be automatically loaded and the details described in the manual flow will appear
- If the user agrees to install the repo, the dialog will hide and the repo will be added to the list and enabled
- If the user disagrees, the dialog closes

**Comment by orels1** [comment]
For the implementation specifics on the `vcc://` link part, I think the backend should send a websocket message of the following shape to the frontend

```json
{
  "messageType": "addRepo",
  "data": <URL>
}
```

And that would kick off the repo flow the same way as described above

**Comment by orels1** [comment]
Almost done with the particular pieces. Just needs some minor feedback/cleanup. All text copy is placeholder



https://user-images.githubusercontent.com/3798928/228085521-5f17d42e-7b77-4f51-998c-a995147128ef.mp4

**Comment by anatawa12** [comment]
Thank you for hard work to adding support for user repositories. 

Could you add way to change packages shown at the top of the list at installation?
My repository contains libraries, experimental tools, tools for developers, and tools for users. I want show tools for users at the top of the included packages list.

**Comment by orels1** [comment]
@anatawa12 it should just grab them in the order they exist in your repository listing, so you would potentially need to adjust the automation code to use a specific order 🤔 


![Image](https://user-images.githubusercontent.com/3798928/228425236-6346b086-8d29-4dfe-ab99-e68f4d1d7313.png)



![Image](https://user-images.githubusercontent.com/3798928/228425260-ef8e9f18-aae0-41b1-96ad-74913d96492b.png)

We could potentially look into some sort of "order" property that you could specify in the github action .yml file, but it is a bit out of scope for this particular release.
Feel free to make a new issue with a feature request though!

**Comment by anatawa12** [comment]
Thank you for replying. I'll reorder elements on my repo. However, I think depending on ordering on the JSON Object is not good for some reasons so I made another feature request. #220

**Comment by orels1** [comment]
This has been released as a part of 2.1.0
