### ISSUE TITLE
Add support for an `id` field in Repo Listings

### ISSUE THREAD

**Issue by orels1** [vrchat-community/creator-companion#211]
User repository listings do not have any unique identifiers (beyond the URL), which causes some issues when working with them. We should add an `id` field before we mass deploy this functionality, with the same requirements as the `id` field on the individual packages.

For repos that do not have that field populated - the frontend will fall back to the url, but we should adjust our automation to require the id field to be specified.

**Comment by orels1** [comment]
This is implemented inside the application, but it still needs to be done on the automation side to ensure people use the new field.

Also I discovered that we do not request people to supply a `url` field even though we deserialize it, so we should note that and ensure our automation does it as well

**Comment by anatawa12** [comment]
Should I add id field to my repositories before release of VCC with user repo support? I'm worried for adding id property after releasing vcc with user repo support break local configuration. I think it could be considered by VCC as changing id of repository from url to id.

**Comment by orels1** [comment]
@anatawa12 if you can, you should add the id whenever you get a moment.
We have fallbacks in place, and the repository URL will still be prioritized when adding a new repo to your settings, so nothing should break even if you don't have the `id` for a while.

This change mostly affects existing users, and everything should keep working correctly for anyone who is already using your packages. But anyone who starts using your stuff for the first time after 2.1.0 release - will be able to leverage the new `id` field for a bit of a cleaner data structure behind the scenes.

**Comment by orels1** [comment]
This has been released as a part of 2.1.0
