### ISSUE TITLE
[FEATURE] Default window resolution

### ISSUE THREAD

**Issue by Realmlist** [vrchat-community/creator-companion#215]
**Is your feature request related to a problem? Please describe.**
I used to be able to select the default window size in the settings tab prior to the WebView2 update. 
I cannot find that option anymore after the update, now VCC appears small with scroll bars all over and I have to manually resize the window every time I launch VCC.

**Describe the solution you'd like**
Reimplement the function to choose a default window resolution.

**Describe alternatives you've considered**
Manually resizing the window every time I launch VCC.

**Comment by orels1** [comment]
VCC remembers the window size and position as of 2.2.x
