### ISSUE TITLE
[BUG] Avatars Project migrated into Udon Project

### ISSUE THREAD

**Issue by Miner28** [vrchat-community/creator-companion#22]
**Describe the bug**
When migrating SDK3 Avatar Project via VCC, it migrates as Udon World with Audio Link, UdonSharp, and Worlds SDK but also includes Avatar 3.0 Manager + Avatars SDK

**To Reproduce**
1. Select SDK3 Avatar Project
2. Migrate 
3. Observe

**Expected behavior**
Only Avatars SDK3 and Avatar Manager is included.

**Screenshots**
![image](https://user-images.githubusercontent.com/1560327/203661994-7619154d-cbf8-45fa-b378-02d820eed23a.png)
![image](https://user-images.githubusercontent.com/1560327/203663077-46e42ab7-e16d-4549-8baf-2c044721aac5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro - Czech Locale
 - Version 22H2

**Comment by momo-the-monster** [comment]
Ah, the issue is probably that AudioLink is automatically detected, removed and replaced with the VPM version, which has UdonSharp as a dependency, thus bringing in the Worlds SDK. We may need to remove that for the time being.

**Comment by Metamaniac** [comment]
@momo-the-monster Can confirm as a seperate issue- importing AudioLink into an avatar project does automatically import the normally blocked Worlds SDK/U# and break things.

**Comment by momo-the-monster** [comment]
@Metamaniac - that would be best tracked as a separate issue, if you wouldn't mind. We'll also work with the AudioLink team to figure out the best way to handle the World/Avatar package split.
