### ISSUE TITLE
Add vcc:// links to Package Listing Templates

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/creator-companion#223]
The "Add to VCC" buttons should use the new scheme in both [template-package-listing](https://github.com/vrchat-community/template-package-listing) and [template-package](https://github.com/vrchat-community/template-package).

**Comment by orels1** [comment]
Template Package Listing PR is up here: https://github.com/vrchat-community/template-package-listing/pull/5

**Comment by orels1** [comment]
Template Package PR is up as well: https://github.com/vrchat-community/template-package/pull/4

**Comment by orels1** [comment]
A little preview of the changes

https://user-images.githubusercontent.com/3798928/229009828-c081d510-87ac-46b6-b890-06e739d3fd1c.mp4

**Comment by orels1** [comment]
This has been released as a part of 2.1.0
