### ISSUE TITLE
[BUG] vpm-resolver appends `&time=<unixtime>` to end of the url and makes 404

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#226]
**Describe the bug**
vpm-resolver appends `&time=<unixtime>` to end of the url so if the url doesn't have `?`, the server will returns 404

**To Reproduce**
1. remove com.vrchat.base folder in Packages
2. open unity project
3. open VPM resolver and click resolve
4. ``[ERR] Couldn't download package from url https://github.com/vrchat/packages/releases/download/3.1.13/com.vrchat.avatars-3.1.13.zip&time=133248080290384747: NotFound``

**Expected behavior**
I think it's much better to not append current time because changing url will be stress to CDNs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 / macOS
 - Version vpm-resolver 0.1.17

**Additional context**

Many user repositories (by me, bdunderscore, lilxyzw) workarounds this problem by appending `?` at the end of url like `https://vpm.anatawa12.com/avatar-optimizer/package-0.0.1.zip?`.

**Comment by owlboy** [comment]
Additionally, it breaks your project when it hits a 404 like that. Please look into allowing the package resolver to recover from a 404 on a package it expects to be able to download. 

I had to go and use the `vpm add package` to re-install the resolver, worlds SDK and UdonSharp to fix my project. 🙏 I'm glad I have both tools!

**Comment by owlboy** [comment]
It appears template projects are also totally busted right now due to this. Unity is stuck in this state after opening the template project and telling it to download what it needs.
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/237349/230676716-9c1d9556-580e-471d-bdb3-42a0b35de343.png">

**Comment by anatawa12** [comment]
It looks this problem is fixed in v0.1.18 but this is still a issue for projects with v0.1.17 / older so I want to keep this issue opened until the fix for old projects (vrchat-community/package-list-action#10) is implemented.
