### ISSUE TITLE
[BUG] Discrepancy between the Latest Version of the SDK and the version of the SDK when creating a new project

### ISSUE THREAD

**Issue by esperecyan** [vrchat-community/creator-companion#229]
**Describe the bug**
Discrepancy between the Latest Version of the SDK and the version of the SDK when creating a new project.
The Latest Version of the SDK is 3.1.11 and the Installed Version of the SDK when creating a new project is 3.1.13.

**To Reproduce**
1. Create New Project on CreatorCompanion.
2. Confirm that the Latest Version of the SDK is 3.1.11.
3. Confirm that the Installed Version of the SDK is 3.1.13.

**Expected behavior**
The Latest Version must be 3.1.13.

**Screenshots**
![](https://user-images.githubusercontent.com/3625160/229330159-d9c26611-550d-41e3-8f47-639b9822adb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - CreatorCompanion Version v2.0.4

**Additional context**
I would like to have this issue resolved as soon as possible because SDK 3.1.13 has backward incompatible changes.
https://github.com/esperecyan/UniVRMExtensions/issues/8

**Comment by esperecyan** [comment]
I have confirmed that the download from the Manual SDK Installation section is SDK 3.1.13.
https://vrchat.com/home/download

**Comment by esperecyan** [comment]
I also looked into migrating the Legacy project and found that SDK 3.1.13 is installed.

**Comment by anatawa12** [comment]
The actual latest version is 3.1.13 and fakely shown as 3.1.11 because of #129.

**Comment by orels1** [comment]
This has been addressed in 2.1.0
