### ISSUE TITLE
[BUG] Adding AudioLink directly to an Avatar project automatically bypasses sanctions preventing Worlds SDK/U# from importing.

### ISSUE THREAD

**Issue by Metamaniac** [vrchat-community/creator-companion#23]
**Describe the bug:**
*See title.*

**To Reproduce:**
1. Go to an Avatar Project
2. Scroll down to AudioLink in the Curated Packages
3. Click on Add

**Expected behavior:**
A warning message is displayed in a similar fashion to directly attempting to add the Worlds SDK/U# to an Avatar project (as for the time being, U# is a hard-dependency).

**Desktop:**
 - OS: Win10
 - Version 1.0.4

**Additional context**
Sister issue to #22

**Comment by pema99** [comment]
Addendum: This happens even on a completely new avatar project created via VCC. It is not specific to any project.

**Comment by momo-the-monster** [comment]
Closing this out with the [release of 1.0.5](https://vcc.docs.vrchat.com/news/release-1.0.5#changelog) which hides away incompatible packages (ie adding a package which requires the World SDK to a project that contains the Avatar SDK). 

AudioLink itself was updated to no longer require either Avatars nor Worlds, and this should not be an issue for other packages moving forward.
