### ISSUE TITLE
[BUG] Package versions are mixed in dropdowns

### ISSUE THREAD

**Issue by TekkyNeko** [vrchat-community/creator-companion#230]
**Describe the bug**
vrc-curated.json and vrc-official.json have the incorrect version order inside of the VCC.
When you open any VCC project under manage project, the latest version is the incorrect version, showing the "latest version" as an old version. lets use the VRChat Package Resolver Tool as an example. The true latest version is 0.1.17, but due to version 0.1.9 being at the very bottom of the vrc-official.json at line 1442 instead of 0.1.17, it places version 0.1.9 at the top of the drop down and makes it think that is the latest version.

**To Reproduce**
1. Go to any project, click on manage project
2. open the drop down of any official or curated package, the order will either be flipped or mixed around

**Expected behavior**
The most up to date packages at the top of the drop down menus, while the oldest ones are at the bottom, letting the latest version be correct and the update button to appear

**Screenshots**
list shown in drop down.
![image](https://user-images.githubusercontent.com/4554597/229330182-f4c0e35d-d89e-40d1-9aea-4a7d78fddf6a.png)
top of the same package inside the json, which is version 0.1.10, which is at the bottom of the VCC drop down.
![image](https://user-images.githubusercontent.com/4554597/229330358-2f7702fc-f081-4212-81b9-d42456cb96e5.png)
side by side comparison of latest package not being the latest package due to this issue
![image](https://user-images.githubusercontent.com/4554597/229330216-e241d61d-d21f-4d9a-92f8-97f86f9ebc95.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (22H2)
 - VCC Version: 2.0.4 

**Additional context**
The solution:
simply fixing the order inside of the [curated index](https://vrchat-community.github.io/vpm-listing-curated/index.json) and the [official index](https://vrchat.github.io/packages/index.json) jsons will solve this issue completely.

Canny: https://feedback.vrchat.com/creator-companion-beta/p/vcc-204-does-not-show-update-icon-for-sdk-3113

**Comment by anatawa12** [comment]
Relates #129.

**Comment by orels1** [comment]
This has been fixed in 2.1.0
