### ISSUE TITLE
[BUG] "Path to a Unity Editor is not set, you will be unable to open projects."

### ISSUE THREAD

**Issue by CosmicCrimson** [vrchat-community/creator-companion#232]
I tried logging into my creator companion today to upload an avatar I have but I was met with that prompt. I tried uninstalling and reinstalling creator companion and it was still there. I tried updating it but it wouldn't update even though it says it needs to be. I have unity installed and I can upload avatars through that but I don't know what else to do.

**Comment by TacoTaco123456** [comment]
Has anyone figured this out? I'm having the same problem, I reinstalled the CC and Unity but it still says the same. And I can´t set it up, please help!

**Comment by momo-the-monster** [comment]
Closed to merge issue with #305.
