### ISSUE TITLE
Check and Update Creator-Facing Docs

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/creator-companion#233]
~~We've got some PRs for the main VCC Docs:~~

- https://github.com/vrchat-community/vrc-package-manager/pull/176
- https://github.com/vrchat-community/vrc-package-manager/pull/301

We'll also want to do a final check of the docs and automation for the related repos:

- [x] https://github.com/vrchat-community/template-package
- [x] https://github.com/vrchat-community/template-package-listing
- [x] https://github.com/vrchat-community/package-list-action

@orels1 is working on updating the docs for managing community repos:
- [x] GUI Instructions
- [x] CLI Instructions

**Comment by orels1** [comment]
This has been released as a part of 2.1.0
