### ISSUE TITLE
[BUG] VCC window is not activated when we click add-repo URL if VCC is running.

### ISSUE THREAD

**Issue by Sayamame-beans** [vrchat-community/creator-companion#235]
**Describe the bug**
VCC window is not activated when we click add-repo URL if VCC is running.
If VCC is not running, the URL work as expected as in [this video](https://github.com/vrchat-community/creator-companion/issues/219#issuecomment-1489566069).

**To Reproduce**
1. Open VCC
2. access [anatawa12's add-repo URL](https://vpm.anatawa12.com/add-repo)*

*this URL redirects to `vcc://vpm/addRepo?url=https%3A%2F%2Fvpm.anatawa12.com%2Fvpm.json`

**Expected behavior**
When click add-repo URL, VCC window will be activated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit
 - Version 22H2

**Additional context**
GitHub's markdown does not support links that do not start with http ( https://github.com/github/markup/issues/933 ), so several people are handling this by redirecting.

**Comment by momo-the-monster** [comment]
From QA:

NEEDS-WORK Even off the installer link "Add to VCC" does not always bring it to front. Potential repro:
1. Hit 'Add to VCC', observe popup but do not interact. Minimize window
2. Hit 'Add to VCC again, no popup this time (one already exists?)
3. Maximize VCC, cancel popup, minimize
4. Hit 'Add to VCC', still no window maximize, but the popup does happen and you can see it if you manually maximize.

Not 100 on those repro steps, but if you just try using the button a bunch in a row under different conditions you should hit it.
