### ISSUE TITLE
[BUG] Avatars 3.0 Manager not autofilling empty Animator states

### ISSUE THREAD

**Issue by Deskclaw** [vrchat-community/creator-companion#236]
Avatars 3.0 Manager's EmptyClip.anim is not auto-filling empty animator state motions when using Write Defaults All On/Off feature.

Steps to reproduce:
1. Install AV3 Manager version 2.0.19 into an Avatars project via the VCC
2. Configure any avatar with any custom animation controller/any animation layers with states with unassigned Motions.
3. Within AV3 Manager, slot in avatar descriptor, select WD tab. Note text saying that empty states exist and will be autofilled. 
4. Select Set WD Off *or* Set WD On, it doesn't work with either. 
5. See error shown in screenshot, below.

**Expected behavior**:
Expected behavior is that empty states will have the Motion field automatically filled with EmptyClip.anim .

Screenshot:
![av3managernotmanaging](https://user-images.githubusercontent.com/27918349/230807534-7a9ea4b7-e417-4696-a043-11b3121346c1.png)

OS: Windows 10 Pro version 22H2
VCC version: v2.1.0
Avatars 3 Manager affected version: 2.0.19

Notes:
in AV3 Manager 2.0.18, this feature works as intended.

**Comment by BluWizard10** [comment]
I've already reported this bug (I'm the one responsible for discovering this issue). This has been fixed as of AV3 Manager v2.0.20.

Unfortunately, v2.0.20 is not added yet in the VCC. So for now, stick with v2.0.18.

**Comment by BluWizard10** [comment]
We are awaiting on this [Pull Request 4](https://github.com/vrchat-community/vpm-listing-curated/pull/4) on the vpm-listing-curated page. Once that is merged, then this issue will be resolved.

**Comment by BluWizard10** [comment]
@Deskclaw As of this writing, Avatars 3.0 Manager v2.0.20 is now available in the Creator Companion. That version fixes the issue that you are currently experiencing.

Can you please update to that version and verify that v2.0.20 has fixed this issue for you as well?

**Comment by momo-the-monster** [comment]
Closed due to inactivity from OP.
