### ISSUE TITLE
I can't creat a project from vcc

### ISSUE THREAD

**Issue by lonelyyooz** [vrchat-community/creator-companion#237]
![image](https://user-images.githubusercontent.com/130339267/230833978-7d222d86-881f-4b04-a452-d4259cf26fa3.png)

I will stay on this interface for a long time and then return to this interface

**Comment by momo-the-monster** [comment]
@lonelyyooz - we'll need some more info to figure out what's going on . What template are you using? Can you try creating the project in a different folder and with a different name?

**Comment by momo-the-monster** [comment]
Closed due to inactivity.
