### ISSUE TITLE
[BUG 2.1.0] VCC UI becomes unavailable when trying to add a community repo listing which contains a pre-release version with pre-releases being disabled

### ISSUE THREAD

**Issue by techanon** [vrchat-community/creator-companion#238]
**Describe the bug**
When trying to add a community repo that has a package which contains _only_ a pre-release version, VCC stops working (specifically the UI itself is no longer available).

**To Reproduce**
1. In VCC Packages tab, disable Show Pre-releases
2. Go to https://vpm.techanon.dev
3. Click on Add To VCC (could also add the json manually too, either one causes the bug)
4. Examine VCC no longer having a UI rendered

**Expected behavior**
Either warn or ignore or something that doesn't break the UI rendering

**Screenshots**
![image](https://user-images.githubusercontent.com/1837484/230964147-8c4fb870-3676-45bb-856b-39bbc8a66634.png)

**Additional context**
I am uncertain if this is caused by the fact that one of the repos has nothing but pre-release, or if it's the fact that there's a pre-release at all and the Show Pre-releases is disabled.

**Comment by orels1** [comment]
This bug also affects the Package Resolver, causing the Editor Window to throw errors when pre-release packages are disabled

**Comment by orels1** [comment]
It will now show up like this in the VCC:


![Image](https://user-images.githubusercontent.com/3798928/232156369-bd4e754a-c601-4da2-9f17-67ff73b63087.png)
