### ISSUE TITLE
[BUG] VCC does not apply package migration to legacy non-VCC packages in VCC projects

### ISSUE THREAD

**Issue by Metamaniac** [vrchat-community/creator-companion#24]
**Describe the bug:**
For VCC-upgraded projects that have legacy versions of VRWorldToolkit, EasyQuestSwitch, AudioLink, or AV3Manager installed, "adding" the curated VPM-versions of those prefabs does not properly remove the old versions and migrate data, instead installing the VPM-versions alongside the legacy ones and causing script errors due to duplicate scripts.

**To Reproduce:**
1. Have a VCC project containing legacy versions of any of the (currently) 4 curated packages
2. Click on "Add" for any/all of the new VPM-versions of those packages
3. Check Unity

**Expected behavior:**
VCC does a check for the existance of legacy packages during the process of adding a curated VPM-version, and appropriately performs similar migration functions to migrating non-VCC projects to VCC.

**Desktop:**
 - OS: Win10
 - Version 1.0.4

**Additional context**
For packages like EasyQuestSwitch, removing the legacy versions in Unity *either before or after* installing the VPM-version results in lost data (presumably as list entries are being stored as components on a gameobject). VCC's migration of non-VCC projects seems to preserve the data somehow, so hopefully better handling of upgrading prefabs in VCC projects to VPM versions will prevent accidental data loss 😅

**Comment by momo-the-monster** [comment]
Feature added in next release!
