### ISSUE TITLE
[BUG 2.1.0] VCC fails to import a VPM asset (vauge error output)

### ISSUE THREAD

**Issue by techanon** [vrchat-community/creator-companion#240]
**Describe the bug**
VCC is failing to import an asset. It spits out some un-specific error.

**To Reproduce**
1. https://vpm.techanon.dev and add to VCC (requires pre-release)
2. Attempt to add to a project
3. Check the logs for errors

**Expected behavior**
The package should succeed on importing.

**Screenshots**
The logs spits out twice `One or more errors occurred. (Object reference not set to an instance of an object.)`
![image](https://user-images.githubusercontent.com/1837484/230993707-716f2fd6-0530-4c43-94f0-bd6a115afba9.png)

**Comment by techanon** [comment]
Originally thought it was tied to legacy folders, but I removed that entire part from the json and still failing in the same way. Continuing to test things.

**Comment by orels1** [comment]
Gitlab doesn't supply a Content-Disposition: attachment header, which is what the VCC is checking for, which is probably unnecessary.

This currently causes your package to fail to download

**Comment by esperecyan** [comment]
Because it does not return content-disposition, GitHub Pages cannot also be used.

**Comment by momo-the-monster** [comment]
This should be fixed in https://github.com/vrchat-community/vrc-package-manager/pull/366
