### ISSUE TITLE
VPM should warn when other packages will be changed

### ISSUE THREAD

**Issue by KhopeshActual** [vrchat-community/creator-companion#247]
- Warn people when installing packages if there are dependencies that will be changed
- Flag for confirming if operations are safe

**Comment by orels1** [comment]
Current WIP of this:


![Image](https://user-images.githubusercontent.com/3798928/232622850-37c753f1-a533-4ea0-8d24-8425569edfae.png)


If there are major upgrades - it will look like this instead:


![Image](https://user-images.githubusercontent.com/3798928/232622951-4c237447-3fea-4d7d-93b4-ddc077686f40.png)

I still need to double-check if we properly validate if the package will try to upgrade dependencies in a way that makes them incompatible with other packages in the manifest to determine how deep the warnings should go

**Comment by orels1** [comment]
Added reporting of the conflicting versions

![Image](https://user-images.githubusercontent.com/3798928/232886421-a6111a52-cfcf-44ee-bf57-e43c64f55bc6.png)

**Comment by Happyrobot33** [comment]
> Added reporting of the conflicting versions
> 
> ![Image](https://user-images.githubusercontent.com/3798928/232886421-a6111a52-cfcf-44ee-bf57-e43c64f55bc6.png)

if you click confirm, does this bump all the dependencies then?
