### ISSUE TITLE
[FEATURE]Add patch notes/version to Update button

### ISSUE THREAD

**Issue by jendaviswilson** [vrchat-community/creator-companion#25]
**Is your feature request related to a problem? Please describe.**
Update! button lacks context--are we updating packages?  VCC itself?  What's getting updated?  Do I need to close projects first? etc

**Describe the solution you'd like**
Add a link or more info

**Comment by orels1** [comment]
We're adding a link to the patch notes and version info as a part of this work: https://github.com/vrchat-community/creator-companion/issues/40#issuecomment-1520331911
