### ISSUE TITLE
[BUG] com.vrchat.core.bootstrap cannot download vpm-resolver

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#250]
**Describe the bug**
com.vrchat.core.bootstrap cannot download vpm-resolver.

Bootstrap appends `&cache=` to end of url. this works well with old url contains `?` but does not work url without `?` which is used for now. (this is very similar to #226)

https://github.com/vrchat-community/template-world/blob/e5fa9b20787e3bcff23123894a444962cb4ecfff/Packages/com.vrchat.core.bootstrap/Editor/Bootstrap.cs#L61
https://github.com/vrchat-community/template-avatar/blob/376fbad6e218bef13adfc3a7d88882a9ffd4e4b1/Packages/com.vrchat.core.bootstrap/Editor/Bootstrap.cs#L61

```
var url = $"{bootstrapMatch.Groups[1].Value}&cache={Guid.NewGuid()}";
```

I made pull request to avoid this problem but I think VRChat **should** append `?` to url returned from `https://api.vrchat.cloud/api/1/config` to not break projects with old bootstrap.

**To Reproduce**
1. Download template project from github
2. open template with unity

**Expected behavior**
vpm-resolver is downloaded and vpm-resolver ask user if download missing packages.

**Actual behavior**
Causes error: 
```
Could not download and install the VPM Package Resolver - you may be missing packages. Exception: The remote server returned an error: (404) Not Found.
UnityEngine.Debug:LogError (object)
VRC.PackageManagement.Core.Bootstrap/<CheckForRestore>d__10:MoveNext () (at Packages/com.vrchat.core.bootstrap/Editor/Bootstrap.cs:41)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder:SetException (System.Exception)
VRC.PackageManagement.Core.Bootstrap/<AddResolver>d__11:MoveNext () (at Packages/com.vrchat.core.bootstrap/Editor/Bootstrap.cs:79)
UnityEngine.UnitySynchronizationContext:ExecuteTasks () (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/UnitySynchronizationContext.cs:107)
```

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Additional context**
Yesterday, I found vpm-resolver downloaded by bootstrap is v0.1.17 (`https://vpm.directus.app/assets/df3b2c11-2ad8-4b6c-9df9-9d7e1782384b?download`) which is broken with #226 so I started writing issue about that.
However, to ensure this is not misunderstanding I tested again and another error (described in this issue) is happened and I found the vpm-resolver is downloaded from github for now. lol

**Comment by momo-the-monster** [comment]
@anatawa12 - is this still an issue?

**Comment by anatawa12** [comment]
@momo-the-monster for projects with older bootstrap, this is still an issue but with newer bootstrap, no.

**Comment by momo-the-monster** [comment]
Thanks - unfortunately, the bootstrap is the one thing we cannot really update. I'll close this out now, thanks.

**Comment by anatawa12** [comment]
> Thanks - unfortunately, the bootstrap is the one thing we cannot really update in existing projects. I'll close this out now, thanks.

That's true but you can fix for old bootstrap by just adding '?' at the end of the url returned by https://api.vrchat.cloud/api/1/config

**Comment by ophura** [comment]
momo just hates us 🥹
