### ISSUE TITLE
[BUG] White screen

### ISSUE THREAD

**Issue by nikorue** [vrchat-community/creator-companion#251]
**Describe the bug**
white screen, fresh install

**To Reproduce**
Open Creator Companion

**Expected behavior**
Creator Companion with anything but white screen

**Screenshots**
![image](https://user-images.githubusercontent.com/67581183/232210243-a220f107-6e63-4b66-b6c6-e7f9036a7096.png)

**Desktop (please complete the following information):**
 - OS: Win 11 22H2 22621.1555 
 - Version  2.1 VCC

**Additional context**
Edge webview is installed

**Comment by momo-the-monster** [comment]
Closed for lack of follow-up.
