### ISSUE TITLE
[BUG] Versions are not correctly ordered by semver if it's from multiple repositories

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#252]
**Describe the bug**
If we add multiple repositories provides same package id (and might be same versions), versions from one repository will be shown after versions from another one. 
This make us harder to find some versions only by one repository.

**To Reproduce**
1. Add `https://vpm.nadena.dev/vpm.json` to your repositories
2. Add `https://vpm.nadena.dev/vpm-prerelease.json` to your repositories
3. Enable Pre-Release Packages
4. See versions list of Modular Avatar

**Expected behavior**
1.5.0-beta-2 will be shown above 1.4.5

**Actual behaviour**
1.5.0-beta-2 will be shown below 1.0.0

**Screenshots**
<img width="228" alt="image" src="https://user-images.githubusercontent.com/22656849/232238573-5df036bc-e870-4608-9a92-4775a37fc38d.png">

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version: VCC 2.1.0

**Additional context**
I think VCC should merge packages with same version from multiple repos on the versions list.

**Comment by orels1** [comment]
A couple of further bugs were found here: The version list returns pre-release packages even if pre-release is turned off. The only one that gets filtered out is the Latest.
There are multiple of the same version listed which makes React unhappy.
