### ISSUE TITLE
[BUG] vpm-resolver v0.1.18 uses VRChatCreatorCompanion-Beta

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#254]
**Describe the bug**
vpm-resolver v0.1.18 uses `VRChatCreatorCompanion-Beta` folder. 

**To Reproduce**
1. Ensure VRChatCreatorCompanion-Beta folder is not exists
2. Open Package Resolver window

**Expected behavior**
`VRChatCreatorCompanion-Beta` is not created and load `settings.json` in `VRChatCreatorCompanion` folder.

**Actual behavior**
`VRChatCreatorCompanion-Beta` folder is created. this means `VRChatCreatorCompanion-Beta` folder is used.
If we added some repos onto `settings.json` in `VRChatCreatorCompanion-Beta`, it's visible in the vpm-resolver.

**Workaround**
You can create symlink targets or create copy of `VRChatCreatorCompanion`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Ventura or Windows 11
 - Version vpm-resolver v0.1.18

**Additional context**

With another problem described in ~~#255~~#10, we cannot open package resolver window with community / user packages.

**Comment by momo-the-monster** [comment]
This should be resolved in 0.1.19, can you test?

**Comment by anatawa12** [comment]
It looks good. Thank you.
