### ISSUE TITLE
Cant opem packages[BUG]

### ISSUE THREAD

**Issue by minecraft4days7** [vrchat-community/creator-companion#263]
**Describe the bug**
I cannot open packages anymore. Suddenly stopped working. Changed nothing whatsoever. It has the blue dot saying it will be opened but doesn't actually open the package

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11

![Screenshot 2023-04-23 162651](https://user-images.githubusercontent.com/20520970/233864311-db96f6eb-e466-44df-a83f-095961a8e2be.png)

**Comment by minecraft4days7** [comment]
![image_2023-04-23_163157014](https://user-images.githubusercontent.com/20520970/233864648-f73a11f2-71be-4b22-ab56-1719f361244d.png)

**Comment by Faxmashine** [comment]
Can you try checking Unit's log, to see if something may have gone wrong on Unity's end?

Here's how you can find Unity's and Unity Hub's log files: https://docs.unity3d.com/Manual/LogFiles.html

**Comment by minecraft4days7** [comment]
finally found it! it was a unity issue with my license. i had to revoke it and then add it back 
![image](https://user-images.githubusercontent.com/20520970/236357807-ca9824d6-4f25-496d-8290-3768eaa0c6ff.png)
 thank you for the help!
