### ISSUE TITLE
[BUG] Projects names with a space at the end create two folders

### ISSUE THREAD

**Issue by Faxmashine** [vrchat-community/creator-companion#267]
**To Reproduce**
Create a folder with the Creator Companion with a space at the end.

**Expected behavior**
One folder should be created. Instead, two are created. Neither folder will contain a valid Unity project.

**Notes**
This has been reported by a user. It requires reproduction.

**Comment by 69MichelleDB** [comment]
I stumbled on this bug today by accident and I can confirm you can easily replicate it by just adding a blank space at the end of a project's name when creating it, CC will fail and create two folders.

In case someone needing of a solution to remove the folders stumbles with this post, here's a fix from the Microsoft forums: https://answers.microsoft.com/en-us/windows/forum/all/remove-a-folder-with-space-at-the-end/2db209ad-9e82-41dd-b05b-4ed681845aa9

**Comment by momo-the-monster** [comment]
Fixed in [VCC 2.1.4](https://vcc.docs.vrchat.com/news/release-2.1.4).
