### ISSUE TITLE
[BUG] Version dropdown partially hidden when project name is long

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#269]
**Describe the bug**
Version dropdown partially hidden when project name is long enough to span in two lines

**To Reproduce**
1. Create project with long project name
2. Open project in VCC
3. click version dropdown of the third package on the list
4. Versions dropdown is partially hidden.

**Expected behavior**
Version dropdown should not be hidden by the Search Packages or Manage Packages.

**Screenshots**
BAD
<img width="639" alt="Screenshot 2023-04-27 210057" src="https://user-images.githubusercontent.com/22656849/234858383-0beb46d4-5239-4755-a408-4cf55ca388b0.png">

OK
<img width="639" alt="Screenshot 2023-04-27 210101" src="https://user-images.githubusercontent.com/22656849/234856257-3e46d272-7a33-48c8-b7c0-5171a58d1895.png">

OK
<img width="639" alt="Screenshot 2023-04-27 210139" src="https://user-images.githubusercontent.com/22656849/234856428-73966ce3-2b3e-4572-8e72-1b2c2cdff582.png">

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version VCC 2.1.0

**Additional context**
If we scroll the project view a little, we can see full version list so this is not significant issue.

<img width="639" alt="Screenshot 2023-04-27 210452" src="https://user-images.githubusercontent.com/22656849/234856682-b770e4f8-c34c-4771-a5f3-35df4b126001.png">

**Comment by orels1** [comment]
Just tested - this is no longer the case as of some time ago
Closing the issue
