### ISSUE TITLE
Update templates to 3.2.x

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/creator-companion#271]
Our next SDK version is 3.2.0, we need to update the embedded templates to match.

**Comment by Happyrobot33** [comment]
alongside this, it should be looked into if its possible to make dynamic templates that can define package versions directly using semantic versioning standards, just like the vpmDependencies field

**Comment by momo-the-monster** [comment]
Yep, the next update to the VCC has the templates use ^3.1.x which will support versions up until 4.0.0.
