### ISSUE TITLE
[FEATURE] Notify user if packages were blocked from updating

### ISSUE THREAD

**Issue by Happyrobot33** [vrchat-community/creator-companion#277]
**Is your feature request related to a problem? Please describe.**
Yes, the related issue is https://github.com/vrchat-community/creator-companion/issues/275. The issue was found to be with UdonSharp itself, so I closed that one. Essentially, if a package doesnt allow for newer versions of another package to install, but another package wants to use a newer version, the newer version of said package will install, but the VCC will fail to bump the other packages without warning the user, leading to issues in the project

**Describe the solution you'd like**
Notify the user that packages failed to be updated due to another package blocking it, and make sure the version of the package that tried to bump other packages does not get applied

**Additional context**
if this is a bit confusing, heres a simplified scenario
**starting configuration**
- package1@1.0.0
- package2@1.0.0
- package3@1.0.0

Lets say package 2 has a new version that updates it to 1.1.0, and that new version requires that package1 is also at 1.1.0 in order to function.
- Package2's new vpmDependency looks like this ```package1: >= 1.1.0```
- Package3's current vpmDependency looks like this ```package1: 1.0.x```

If we select package2 and tell the VCC to install the new version, package 2 will successfully change to 1.1.0, however due to the fact that package 3 requires the minor version to be 0, the VCC will not update package 1 to 1.1.0

This is a problem since package 2 likely requires new features from package 1 if it is trying to bump package 1s version

**Comment by anatawa12** [comment]
Might be a duplicate of https://github.com/vrchat-community/creator-companion/issues/247#issuecomment-1513697598?

**Comment by Happyrobot33** [comment]
Fixed, implemented as of #247 being closed
