### ISSUE TITLE
[BUG] Resolver - Closing a project with the Resolver window open forces a Window Layout reset when reopening the project

### ISSUE THREAD

**Issue by owlboy** [vrchat-community/creator-companion#279]
**To Reproduce**
1. Open the Resolver
2. Quit Unity
3. Reopen the project
4. Observe that you are being forced to reset your entire window layout
5. Begrudgingly accept this
6. Reorganize your windows
7. Make a mental note to never leave the Resolver window open
8. In a few weeks, forget that mental note and return to step one

**Video**

https://user-images.githubusercontent.com/237349/236571545-21098d98-7005-4bae-aa08-2f34f30d0e4b.mp4

**Comment by orels1** [comment]
This should be improved in Resolver 0.1.28
If you still encounter this issue, please let us know!
