### ISSUE TITLE
[BUG] VCC and VPM CLI doesn't recognize Unity Editor

### ISSUE THREAD

**Issue by hoverAdev** [vrchat-community/creator-companion#288]
**Describe the bug**
Creator Companion / VPM CLI refuse to recognize my Unity installation, despite `vpm list unity` not encountering the issue. Using the 📂 icon in Creator Companion to select the editor fails as well. The same error occurs when manually setting the path in `settings.json`, in which case `pathToUnityExe` will be reset to `""`.

**To Reproduce**
1. Open CreatorCompanion
2. Click on Settings
3. Wait
4. The error message "No Unity Editors found, you need a Unity Editor to be able to launch projects via the VCC" will show up

**Expected behavior**
I expected any of the tried methods to correctly identify and set the Unity Editor path.

**Screenshots**
![image](https://user-images.githubusercontent.com/50588936/236985770-d039bcf2-845a-459a-aea5-3e9fa65a517e.png)
![image](https://user-images.githubusercontent.com/50588936/236985810-32a1a390-4814-43b7-8da4-812608e40375.png)
![image](https://user-images.githubusercontent.com/50588936/236985895-ffa5e2e1-5065-4a30-b2a9-0af8d2485d95.png)
![image](https://user-images.githubusercontent.com/50588936/236986785-bc738d1a-0b5a-49ff-b050-8270c8e99d94.png)

**Desktop (please complete the following information):**
 - Guest OS: Windows 11 Insider (Release Candidate)
 - Version: 10.0.22624 Build 22624

**Additional context**
I believe the most likely points of error are the fact that the version of Unity (2021.3.24f1) may be one that is unsupported, and that is somehow causing an error. However, I do not know what in the nature of this newer version would cause this. Another possible failure point is that Unity is installed in a nonstandard location, and not on the C drive. If VCC cannot recognize Unity installations on secondary drives, such as my G drive, that could also be responsible for this error. Lastly, it is of note that I am running Windows as a guest VM under Unraid 6.11.5. While I cannot imagine how this VM status would cause this error, it is true that VRC does not run on this guest, which likely makes it very different from the typical setup used with VCC.

**Comment by hoverAdev** [comment]
Both tools (VCC and CLI) were downloaded and installed today. VCC is version v2.1.1 and CLI is version 0.1.16, which should be the latest at time of writing.

**Comment by Sophilautia** [comment]
I am also experiencing this issue. I am a new user to CreatorCompanion and the VRChat SDK in general.

![image](https://github.com/vrchat-community/creator-companion/assets/10488699/082ec960-65ec-4204-a43c-a920e440a848)

After clicking 'I already have Unity' on the next page and selecting Unity.exe in my D drive, this error shows up:

![image](https://github.com/vrchat-community/creator-companion/assets/10488699/521d49f5-4b07-4252-84a9-8583a5de4bce)

I am also running Unity 2021.3.24f1.

**Comment by momo-the-monster** [comment]
Closed to merge issue with #305.
