### ISSUE TITLE
[BUG] No Unity Editors found, you need a Unity Editor to be able to launch projects via the VCC

### ISSUE THREAD

**Issue by yayadi007** [vrchat-community/creator-companion#293]
**Describe the bug**
Everytime I try to set it up it always says No Unity Editors found, you need a Unity Editor to be able to launch projects via the VCC

**Desktop (please complete the following information):**
 - OS: windows 10

**Comment by momo-the-monster** [comment]
Closed to merge issue with #305.

**Comment by momo-the-monster** [comment]
Closed to merge issue with #305.
