### ISSUE TITLE
[BUG] Packages relates to Worlds should depends on VRCSDK instead of clientsim

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#297]
### Describe the bug

Packages relates to Worlds should depends on VRCSDK instead of clientsim.

### To Reproduce

1. Open Package Maker
2. Set Related VRChat Package to Worlds
3. Select some folder and id
4. Click convert Assets to Package
5. Generated package.json declares dependency relationship to clientsim

### Expected behavior

Generated package.json should declares dependency relationship to VRCSDK instead.

### Related Product

vpm-resolver (Package Resolver)

### Product Version

0.1.19

### OS

Windows 11

**Comment by anatawa12** [comment]
@momo-the-monster 

I'm sorry for pinging.

Recent [developer update][dev-upd] announces VRCSDK will include ClientSim and UdonSharp in the next release.

[dev-upd]: https://ask.vrchat.com/t/developer-update-14-september-2023/19931

I don't know much about how the new (post-2.1.3) VCC will resolve packages but I think this should be fixed in/until the next package resolver so I ping.

**Comment by momo-the-monster** [comment]
@anatawa12 - it is fine to ping me about this, thank you. I will make sure this is updated with the new release. Also FYI, I just [opened an issue](https://github.com/anatawa12/unity-gist-pack/issues/8) to prepare one of your packages for the upcoming SDK changes.

**Comment by momo-the-monster** [comment]
Fixed in Resolver 0.1.22.
