### ISSUE TITLE
[BUG] removing legacyFiles is not working if legacyFolders is not specified

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#299]
### Describe the bug

removing legacyFiles is not working if legacyFolders is not specified

### To Reproduce

1. Add https://anatawa12.github.io/vpm-repo-for-vcc-bug-testing/ to your VCC
2. Download and add [this project](https://github.com/vrchat-community/creator-companion/files/11524046/vpm-legacy-files-test.zip) to VCC
3. Open the project with VCC
4. Add `Legacy File with Name` or `Legacy File With Path`

### Expected behavior

`Assets/legacyFileWithName.txt` or `Assets/legacyFileWithPath.txt` should be removed

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.1

### OS

Windows 11

### Additional context

There are no logs like `Looking for Legacy Packages to Upgrade by Scanning Folders within <package>` when we're installing `Legacy File with Name` or `Legacy File With Path`

If we added legacyFolders attribute, `Looking for Legacy Packages to Upgrade by Scanning Folders within <package>` is shown but because of #281, no files are removed. (you can test with `legacyFiles with Name with legacyFolders` package from same repository)

**Comment by anatawa12** [comment]
I confirmed this issue still exists in 2.1.2

**Comment by momo-the-monster** [comment]
Thanks! This should be fixed in the next release.

**Comment by anatawa12** [comment]
I confirmed this still is a issue in VCC 2.2.2....

**Comment by momo-the-monster** [comment]
Thank you for your response, much appreciated.

**Comment by anatawa12** [comment]
bump. this is still a issue in VCC 2.2.5.

**Comment by orels1** [comment]
This should be addressed in the 2.3.0 open beta: https://github.com/vrchat-community/creator-companion/releases/tag/2.3.0

**Comment by orels1** [comment]
This has been released to live with version 2.3.0: https://vrcpm.vrchat.cloud/vcc/Builds/2.3.0/VRChat_CreatorCompanion_Setup_2.3.0.exe
