### ISSUE TITLE
Japanese characters are not preserved in backups [BUG}

### ISSUE THREAD

**Issue by nthubgit** [vrchat-community/creator-companion#3]
**Describe the bug**
When a backup is made of a project with files that have Japanese characters in the filename, Mojibake (https://en.wikipedia.org/wiki/Mojibake) occurs.

For example,

Before backup: 更新履歴.txt
After backup: 譖ｴ譁ｰ螻･豁ｴ.txt

This doesn't happen to the migrated files, only the backup.

**To Reproduce**
See above

**Expected behavior**
Filenames should be preserved.

**Screenshots**
https://puu.sh/JjhOd/d8c881e641.png

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [Build 19044]

**Comment by momo-the-monster** [comment]
Fixed in 1.0.1 by constructing the FastZip object with a `new ZipEntryFactory() { IsUnicodeText = true };` to ensure that entries with Unicode text are saved.
