### ISSUE TITLE
[FEATURE] add ability to install specific version of package via vpm command

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#30]
**Is your feature request related to a problem? Please describe.**
We cannot install specific version of package via vpm command.

**Describe the solution you'd like**
Add optional version argument after package name.

```
vpm add package <packageName> [version]
```

**Additional context**
We can install specific version of package via VCC so it should be possible.

**Comment by orels1** [comment]
This is now possible using `vpm add package <packageName>[@version]` syntax
e.g. `vpm add package com.vrchat.base@3.5.1`
