### ISSUE TITLE
Creator Companion doesn't detect my unity editor

### ISSUE THREAD

**Issue by Th3Zu** [vrchat-community/creator-companion#304]
Hello! I just installed VRCHAT creator companion because i wanted to try using an existing project that i had on unity, and when i try to set a path for the editor, gives me a null statement (2023-06-02 12:49:30.057 -04:00 [INF] Failed to update the path to Unity: null), and i can't really find any solution to it.

**Comment by momo-the-monster** [comment]
@Th3Zu - the Creator Companion requires the [Current Supported Unity Version](https://docs.vrchat.com/docs/current-unity-version), which is 2019.4.31f1. Is this the version you selected? If not, let the VCC install the correct version for you.

**Comment by momo-the-monster** [comment]
Closed to merge issue with #305.
