### ISSUE TITLE
[FEATURE] Expand valid Unity Versions, Show a Better Error Message

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/creator-companion#305]
**Is your feature request related to a problem? Please describe.**
Users are confused by the vague error message that appears when choosing an unsupported Unity Version.

**Describe the solution you'd like**
The VCC should show a more informative message, and accept a few more Unity versions.

I believe this error is responsible for #293 #232 #288 #300 #152 #304, which will be closed to track them all here.

**Comment by MarcFichtelVRC** [comment]
Ready for QA:
* Get and install [VCC v2.1.1-better-errors.1_Release.zip](https://github.com/vrchat-community/vrc-package-manager/releases/tag/2.1.1)
* Run VCC
* Test Case 1: With no unity editor installed, VCC logs should indicate that supported editor is installed
* Test Case 2: With an unsupported editor installed, VCC logs should indicate that the installed version(s) are not supported, and list the supported versions
* Test Case 3: With a supported version installed, everything should function as usual

List of currently supported versions:
* 2019.4.40f1
* 2019.4.31f1
* 2019.4.31f1c1
* 2019.4.30f1
* 2019.4.29f1

**Comment by momo-the-monster** [comment]
Now merged and released!
