### ISSUE TITLE
Websocket Fixes

### ISSUE THREAD

**Issue by KhopeshActual** [vrchat-community/creator-companion#307]
First, repro the issues where the websocket fails.
Then see if we can set a timeout.

**Comment by momo-the-monster** [comment]
Some [notes I made](https://github.com/orgs/vrchat-community/projects/1/views/10) trying to track the project connection flow.

**Comment by MarcFichtelVRC** [comment]
Note to self: The code in question lives in `VCCApp/Services/ApiServer.HandleWSRequest()` (around line 192)

**Comment by MarcFichtelVRC** [comment]
Repro steps:
* Open VCC
* Open a Unity project
* Add or remove a pkg from the open project
* While Unity is compiling, attempt to close VCC

Expected behaviour:
* VCC closes (after a timeout)

Actual behaviour:
* VCC hangs indefinitely

**Comment by MarcFichtelVRC** [comment]
Ready for QA, repro steps above

**Comment by momo-the-monster** [comment]
This is merged and released!
