### ISSUE TITLE
[BUG] vpm-resolver may adds `com.vrchat.*` after `!com.vrchat.core.*`

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#31]
**Describe the bug**
vpm-resolver may adds `com.vrchat.*` after `!com.vrchat.core.*`.
This may exclude some part of vpm-resolver and make it fails to resolve package.

**To Reproduce**
1. Create some Project which uses vpm-resolver (Any project is acceptable.)
2. Remove `com.vrchat.*` line from `Packages/.gitignore`.
3. Update, Downgrade, or Resolve package in Package Resolver window.
4. Now, `com.vrchat.*` is added to last which may be after `!com.vrchat.core.*`.
This excludes newly added files in vpm-resolver and breaks vpm-resolver.

**Expected behavior**
I think VPM Resolver should not add `com.vrchat.*` to gitignore if `/*/` is already listed.

**Screenshots**

**Desktop (please complete the following information):**
First Env
 - OS: macOS
 - Version 13.0 22A380 arm64

Second Env
 - OS: Windows
 - Version 11 22H2

**Additional context**

**Comment by float3** [comment]
This also happened with the Audiolink project

**Comment by Faxmashine** [comment]
Thank you for reporting this issue!

You mention in step 2 that you removed `com.vrchat.*` from `Packages/.gitignore`.

Can you please post the full contents of your `.gitignore` before that step?

I'm having trouble reproducing the issue, as the file appears to be different on my end:
```
/*/
!com.vrchat.core.*/
```

**Comment by anatawa12** [comment]
At first

```gitignore
/*/
com.vrchat.*/
!com.vrchat.core.*/
```

After step 2. This is exactly same as [gitignore in template](https://github.com/vrchat-community/template-udonsharp/blob/51b5173790abf6614aa59733e5548cad00a09b1b/Packages/.gitignore)
```gitignore
/*/
!com.vrchat.core.*/
```

After step 3

Tested with removing some packages and then click `Resolve All` button

```gitignore
/*/
!com.vrchat.core.*/
com.vrchat.*/
```

Expected pattern 1

```gitignore
/*/
!com.vrchat.core.*/
```


Expected pattern 2

```gitignore
/*/
com.vrchat.*/
!com.vrchat.core.*/
```

**Comment by anatawa12** [comment]
I don't konw when but this issue is resolved in some earlier release.
Thank you for fixing issue!
