### ISSUE TITLE
Add Creator Docs search to Learn page

### ISSUE THREAD

**Issue by KhopeshActual** [vrchat-community/creator-companion#310]
May require help from a web dev to integrate a search of our Algolia index with a widget like what we have on all the doc sites.

Desire is to have the search box available from the Learn screen, offering autocomplete searches as it does now, opening up chosen results in user's default browser.

**Comment by orels1** [comment]
Added the docsearch widget to the Learn page, similar to our other docs pages

**Comment by momo-the-monster** [comment]
Now available in VCC 2.1.2!
