### ISSUE TITLE
I think version matching page should be redirected to releases in creator docs

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#312]
Currently, there're two place to see changelog of VRCSDK: [Version Matching in VCC Docs](https://vcc.docs.vrchat.com/guides/version-matching/) and [Releases in Creator Docs](https://creators.vrchat.com/releases).

I think this can cause difference between two docs (see #284) so I think it's better to add unitypackage SDK version information onto Releases in Creator Docs and redirect Version Matching to releases in creator docs.

If we can use JavaScript to redirect the Version Matching page, I think it's better to redirect based on anchor like `https://vcc.docs.vrchat.com/guides/version-matching#320` to `https://creators.vrchat.com/releases/release-3-2-0/`.

**Comment by Faxmashine** [comment]
We have added an admonition to the top of the version matching page:

https://vcc.docs.vrchat.com/guides/version-matching/

> Please refer to the VRChat SDK's [Release Documentation](https://creators.vrchat.com/releases/) page to see the latest information about SDK releases.
