### ISSUE TITLE
[BUG] cant download vcc

### ISSUE THREAD

**Issue by nimhsy** [vrchat-community/creator-companion#320]
### Describe the bug

Cant install creator companion, i tried to do the recent update then VCC started to crash a lot so i uninstalled and now i cant resinstall

### To Reproduce

unsure

### Expected behavior

i expected the app to update and id be able to continue uploads

### Screenshots

![Screenshot (91)](https://github.com/vrchat-community/creator-companion/assets/138348362/99785a1a-6898-4c94-8f71-685dd588e5db)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.1

### OS

Windows 10

**Comment by momo-the-monster** [comment]
@nimhsy - that dialog is telling you that you need to run `CreatorCompanion.exe` with 'elevation', aka run it in administrator mode. However, that looks like the attempt to run the application itself. What happens when you try to run the installer, since you uninstalled it?

**Comment by orels1** [comment]
Im going to close this issue due to inactivity. Feel free to create a new one if the problem persists!
