### ISSUE TITLE
[BUG] White screen no matter what.

### ISSUE THREAD

**Issue by Zemaus2023** [vrchat-community/creator-companion#328]
### Describe the bug

Creator Companion launches to a white screen and white icon even after a fresh install and full file wipe.
Deleting settings file in local did nothing and logs show nothing other than the log being made.

Only thing I can add that was different was that VisualStudio was installed between working and non working use. Even after uninstalling and deleting everything about it it still wont work.

### To Reproduce

1. Launch CC is all I can say.

### Expected behavior

Worked fine earlier in the day.

### Screenshots

![image](https://github.com/vrchat-community/creator-companion/assets/140576722/8e2563b4-f110-4013-9cb6-a4b1b4ace414)
![image](https://github.com/vrchat-community/creator-companion/assets/140576722/efe79ada-0d1b-4282-96ab-fb2945bb9f4e)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.1

### OS

Windows 10

**Comment by momo-the-monster** [comment]
@Zemaus2023 - this symptom is typically caused by an incorrect/missing WebView2 installation. Can you try [the steps here](https://vcc.docs.vrchat.com/guides/faq#what-do-i-do-if-webview2-is-not-installed-correctly)?

**Comment by momo-the-monster** [comment]
Closed for inactivity, feel free to reopen after trying the fix above, thanks!
