### ISSUE TITLE
[BUG] Never Opens, empty logs

### ISSUE THREAD

**Issue by ZornTaov** [vrchat-community/creator-companion#340]
### Describe the bug

I just installed VCC, and trying to run it through the start menu shortcut or the exe directly does nothing except create an empty log file like so `2023-09-01 01:43:14.058 -07:00 [INF] VRCLibLogger Writing logs to C:\Users\[REMOVED]\AppData\Local\VRChatCreatorCompanion\Logs\20230901T014314-2b8869cb73cc4a64bd88ab2b2003ba81-log.txt` this also happens when I start it as administrator.

### To Reproduce

1. Run CreatorCompanion.exe
2. nothing pops up, process instantly closes, no errors

### Expected behavior

it should open?

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.2

### OS

Windows 10

### Additional context

I've got Unity Hub and my Unity installs on my D:/ drive, if that matters.

**Comment by ra0000** [comment]
if notion is running quit it
because of port conflict 5476

**Comment by ZornTaov** [comment]
I do not have notion installed on my computer.  If you meant Norton, I also don't have that installed.  I tried quitting all programs I know I added myself through task manager. I also checked netstat for that port.  I still can't get VCC to run.

**Comment by ZornTaov** [comment]
I have absolutely no idea why, but on a whim I opened it during my vacation and it started up just fine.  The main differences between then and now are I have no external monitors plugged in, and I upgraded both my C and D drives to SSD's, with the C drive going from 512gb with 100gb free, to 2tb.

**Comment by orels1** [comment]
VCC 2.2.4 now uses dynamic ports. The future updates will also include better logging to help you debug.
Please open a new issue if you encounter this again
