### ISSUE TITLE
[BUG] CLI out of date, cannot resolve some packages correctly

### ISSUE THREAD

**Issue by sky1e** [vrchat-community/creator-companion#343]
### Describe the bug

The most recent version of the VPM CLI published most recently is [0.1.17](https://www.nuget.org/packages/VRChat.VPM.CLI). [Recent versions of the SDK](https://github.com/vrchat/packages/releases/tag/3.2.2) (I believe, despite the release notes, anything >=3.1.13) require version 0.1.20 of the resolver library in order to correctly resolve. This results in receiving an inscrutable dependency error when trying to use the CLI to create and manage projects.

Using the CLI to create a new project with the one of the built-in templates and then resolving packages results in a project where VRCSDK fails to load with the following error:
```
Assembly 'Packages/com.vrchat.base/Editor/VRCSDK/Dependencies/VRChat/CreatorCompanion/WatsonTcp.dll' will not be loaded due to errors:
WatsonTcp references strong named Newtonsoft.Json Assembly references: 12.0.0.0 Found in project: 13.0.0.0.
```

The CLI can be used to install a more recent resolver as a Unity package, but the Unity package isn't included in the templates or mentioned anywhere in the [docs page for the CLI](https://vcc.docs.vrchat.com/vpm/cli/).

### To Reproduce

1. Install the VRChat Package Manager Command-line tool: `dotnet tool install --global VRChat.VPM.CLI`
2. Install the templates: `vpm install templates`
3. Create a new project using a template: `vpm new ProjectName Avatar`
4. Resolve VPM packages: `vpm resolve project ProjectName`
5. Open your project in Unity, and discover that VRCSDK fails to load in your fresh project because of a dependency error:
```
Assembly 'Packages/com.vrchat.base/Editor/VRCSDK/Dependencies/VRChat/CreatorCompanion/WatsonTcp.dll' will not be loaded due to errors:
WatsonTcp references strong named Newtonsoft.Json Assembly references: 12.0.0.0 Found in project: 13.0.0.0.
```

### Expected behavior

I expect the CLI to be able to correctly resolve the packages that it adds to my project.

### Related Product

VPM CLI

### Product Version

0.1.17

### OS

macOS / Linux

**Comment by orels1** [comment]
Current VPM CLI should pull the latest available resolver for the unity version in question
Please open a new issue if you still encounter this
