### ISSUE TITLE
[BUG] "Found a Unity Editor with an unsupported version" Error

### ISSUE THREAD

**Issue by MyselfApparently** [vrchat-community/creator-companion#344]
Hello, i encountered this error and looked around for a answer but i couldnt find one. i checked the FAQ and followed the steps like uninstalling the json files under Repos and a few other things that should be solutions but nothing happened. help please!

![image_2023-09-13_172619367](https://github.com/vrchat-community/creator-companion/assets/144960385/d677f0cc-88b3-4709-b3e0-ea7b43ad9cc8)
 IGNORE THIS I JUST MAXIMIZED THE SCREEN AND SAW WHAT I DID WRONG IM SORRY

**Comment by Faxmashine** [comment]
Glad you found a solution! Thanks for trying to contribute.
