### ISSUE TITLE
[FEATURE] default installed packages option on project creation

### ISSUE THREAD

**Issue by WizeWizzard007** [vrchat-community/creator-companion#345]
My feature request isn't related to a problem, more so a quality of life

Add a way to have 'default' packages selected/installed on creating a project

the alternative is to do it manually

As an avatar creator, I end up making multiple projects for avatars. What annoys me is that every time I create a project, I end up having to press add on every single package one by one and wait for it to install preferably before opening the project. A nice solution would be to add a way in settings, maybe under packages. This doesn't seem like it might be too hard to do. maybe a pop-up every time you create a project to ask if you want to apply a pre-determined preset for packages that users can make themselves. 
To my knowledge, this is not a thing.

**Comment by anatawa12** [comment]
For your information: I think official way to install multiple packages first time is to use user templates. This can be used for now. https://vcc.docs.vrchat.com/vpm/templates#user-templates

**Comment by WizeWizzard007** [comment]
Oh my god, I didn't know this existed. I couldn't find anything like it.

**Comment by momo-the-monster** [comment]
Yes! This is exactly what User Templates are for, thanks @anatawa12.
