### ISSUE TITLE
[BUG] VRChat Creator Companion will not install on drive it was downloaded onto.

### ISSUE THREAD

**Issue by Reekitty** [vrchat-community/creator-companion#347]
### Describe the bug

I did install Unity Hub first then downloaded Creator Companion. Attempted to install Creator Companion and received "The drive or UNC share you selected does not exist or is not accessible. Please select another." I uninstalled Unity Hub to see if the Creator Companion would install it after but was not able to get that far in the process. 

### To Reproduce

1. Installed Unity Hub.
2. Downloaded VRChat Creator Companion through the VRChat website.
3. Click on the Steup executable in my downloads folder.
4. Received Error.
5. Uninstalled Unity Hub and tried again.
6. Received the same Error.
![VRChat Creator Companion Error](https://github.com/vrchat-community/creator-companion/assets/145220646/1dbf8d5b-9e30-41cf-a2a2-9962606a9070)

### Expected behavior

Expected VRChat Creator Companion to install

### Screenshots

![VRChat Creator Companion Error](https://github.com/vrchat-community/creator-companion/assets/145220646/0d2c851d-448e-4b9e-8eb2-4fd1694329a0)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.2

### OS

Windows 10

**Comment by momo-the-monster** [comment]
Hi @Reekitty - not sure why the install fails since we don't have any details about the drive which it's trying to use, but you can use the command line to run the Installer with the `/DIR` argument to set its location if needed. 

For example, if I wanted to install the 2.1.3 version to my "F" drive, I could run the following command from the folder where the Setup file is located:
```cmd
VRChat_CreatorCompanion_Setup_2.1.3.exe /DIR = "F:/CreatorCompanion"

Will you give this a try, using a local volume (ie not a Cloud-Service-Mapped drive like OneDrive or Google Drive)

**Comment by Reekitty** [comment]
I am using an external drive (D:). I tried that command in the folder the setup file is located but I received the same error.
