### ISSUE TITLE
[BUG] legacy packages is not working if upgraded by dependencies of other packages

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#349]
### Describe the bug

legacy packages is not working if upgraded by dependencies of other packages.

If VRCSDK Worlds is upgraded by dependencies of other packages, UdonSharp and ClientShim are not removed.

### To Reproduce

1. Create Project with VRCSDK Worlds 3.3.0 and UdonSharp
2. Install packages depends on `com.vrchat.worlds` `3.4.0-beta.1` or later
   You can use `The Package depends on SDK Worlds 3.4.0` in https://anatawa12.github.io/vpm-repo-for-vcc-bug-testing/ for testing.

**Actual Behavior**
UdonSharp is **NOT** removed from the project.

### Expected behavior

UdonSharp is removed from the project.

### Screenshots

<img width="1309" alt="Screenshot 2023-09-20 at 16 15 26" src="https://github.com/vrchat-community/creator-companion/assets/22656849/540651b2-48cc-4ed2-9d9f-e21b0769b32d">

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.3

### OS

Windows 11

### Additional context

This will break unity project so I think this must be fixed BEFORE VRChat SDK 3.4.0 release

Relates to #350

**Comment by anatawa12** [comment]
Sorry, I made a mistake with the title. This issue is about legacy packages, not about legacy folders.

There are another issue about legacy folders: #298

**Comment by momo-the-monster** [comment]
Thanks - working on a fix along with #350.
