### ISSUE TITLE
[BUG] UdonSharp is installed as dependencies even if SDK Worlds 3.4.0-beta.1 is installed

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#350]
### Describe the bug

UdonSharp is installed as dependencies even if SDK Worlds 3.4.0-beta.1 is installed.

### To Reproduce

1. Create Project with VRChat SDK Worlds 3.4.0
2. Install some packages depends on UdonSharp
   I use `KinelVideoPlayer` by https://vpm.niri.la/ or `QvPen` by https://vpm.ureishi.net/repos.json

**Actual Behaviour**

UdonSharp is installed even if VRChat SDK Worlds 3.4.0-beta.1 is installed

### Expected behavior

UdonSharp is not installed becayse UdonSharp is legacy package of VRChat SDK 3.4.0.

### Screenshots

<img width="1287" alt="Screenshot 2023-09-20 at 16 33 21" src="https://github.com/vrchat-community/creator-companion/assets/22656849/529d58e1-866a-496d-8b26-576e9dd2dde9">
<img width="1320" alt="image" src="https://github.com/vrchat-community/creator-companion/assets/22656849/40bb400b-4d20-4c57-a3d5-8fd6448ab40d">

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.3

### OS

Windows 10

### Additional context

This will break unity project so I think this must be fixed **BEFORE** VRChat SDK 3.4.0 release

Relates to #349

**Comment by momo-the-monster** [comment]
@anatawa12 - thanks for reporting, we've reproduced the issue and we're working on a fix.

**Comment by anatawa12** [comment]
This cause is fixed but very similar another case, this still not resolved. I made issue: #356
