### ISSUE TITLE
[BUG] VCC tries to downgrade a package, even though that package is compatible

### ISSUE THREAD

**Issue by hai-vr** [vrchat-community/creator-companion#359]
### Describe the bug

VCC tries to downgrade a package, even though that package is compatible.

1.0.9907 is being downgraded to 1.0.9905, even though 1.0.9907 matches the constraint ^1.0.0

### To Reproduce

- Add https://hai-vr.github.io/vpm-listing/ listing (note: the listing versions may change by the time you test)
- Add the listing given in the front page of https://modular-avatar.nadena.dev/
- Add "Animator As Code" into an Avatars project through VCC packages
- Add "Animator As Code - Modular Avatar" into an Avatars project through VCC packages

Actual behaviour:
Upon adding "Animator As Code - Modular Avatar", a window shows up that tries to downgrade "Animator As Code" 1.0.9907 to 1.0.9905

### Expected behavior

The package "Animator As Code - Modular Avatar" is added to the project

### Screenshots

![image](https://github.com/vrchat-community/creator-companion/assets/60819407/f4a05406-3905-4b58-8f72-7abc51ab3494)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.4

### OS

Windows 10

**Comment by orels1** [comment]
The fix for this is in the works, should be out with the next release

**Comment by momo-the-monster** [comment]
Should be fixed now in [Creator Companion 2.1.5](https://vcc.docs.vrchat.com/news/release-2.1.5), thanks for reporting!
