### ISSUE TITLE
[FEATURE] `-version` option to `vpm add package`

### ISSUE THREAD

**Issue by kurotu** [vrchat-community/creator-companion#36]
**Is your feature request related to a problem? Please describe.**
`vpm add package` just adds the latest version of the package. We can't add the desired version even if latest packages have compatibility issues.

**Describe the solution you'd like**
Add `-version` option or syntax to `vpm add package` command. When it's used, the CLI should add the specified version of the package.

For example:
```
vpm add package foo -version X.Y.Z
vpm add package foo@X.Y.Z (like npm)
```

**Describe alternatives you've considered**
We need to manually downgrade packages after adding latest packages.

**Additional context**
VPM CLI version: 0.1.12

**Comment by Docteh** [comment]
Looks like a duplicate of https://github.com/vrchat-community/creator-companion/issues/30

**Comment by kurotu** [comment]
I missed it. Thank you!
