### ISSUE TITLE
[BUG] Program icon does not contain correct scalings

### ISSUE THREAD

**Issue by Adam-Kay** [vrchat-community/creator-companion#361]
### Describe the bug

The program icon for VRC-CC Windows version does not have the correct scalings embedded within it for the icon to be displayed correctly at different sizes. It contains 1 160x160 icon which looks great at standard size, but once scaled down in Windows becomes pixelated and harder to read. This is related to issue #42.

I have created a new copy to illustrate the difference:

(Scaling the same at max size)
![image](https://github.com/vrchat-community/creator-companion/assets/10010491/1650e2a6-b5a1-40e3-af4f-98e7edbb5190)

(Scaling difference evident at 16px)
![explorer_5ipfarbMZE](https://github.com/vrchat-community/creator-companion/assets/10010491/973c54e9-3417-461b-86b7-5a9f4b2b3cae)

The new copy is available below to view, it contains the original 160px along with 128px, 64px, 48px, 32px, and 16px anti-aliased scalings using _icofx_.

[📂vrccc-icon.zip](https://github.com/vrchat-community/creator-companion/files/12841241/vrccc-icon.zip)

### To Reproduce

Add VRChat Creator Companion shortcut to your start menu, or view it in File Explorer with the "Small Icons" view - you will see the icon is pixelated and hard to read.

### Expected behavior

A correctly anti-aliased icon should be displayed for visual clarity.

### Screenshots

![explorer_DdNWfDYHIY](https://github.com/vrchat-community/creator-companion/assets/10010491/699827bb-ea6e-4b99-82a5-7ec7fd8684b6)
![explorer_5ipfarbMZE](https://github.com/vrchat-community/creator-companion/assets/10010491/97266254-f4b4-4f24-aefb-3d36b6509da4)

#### Start Menu (Win 11)
Before modification             |  After modification
:-------------------------:|:-------------------------:
![before](https://github.com/vrchat-community/creator-companion/assets/10010491/1e09e52e-d531-44db-af68-255046173393)  |  ![after](https://github.com/vrchat-community/creator-companion/assets/10010491/71bba8fc-cf59-42ca-8dd4-048f6a75e1a3)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

v2.1.4

### OS

Windows 11

**Comment by orels1** [comment]
This has been addressed some time ago when we added beta icons.

![image](https://github.com/user-attachments/assets/19cc0570-b50e-4b20-a8ff-bcf1d4759cb7)
