### ISSUE TITLE
[BUG] Custom Project template causing issues

### ISSUE THREAD

**Issue by Centauri2442** [vrchat-community/creator-companion#362]
### Describe the bug

Creator Companion v2.1.4 

VCC currently has a Custom project template which includes the legacy ClientSim and UdonSharp packages. However, because both of those packages are now part of the worlds package, it results in either an error when attempting to create, or incorrectly installs both legacy packages, breaking the project.

### To Reproduce

1. Open creator companion
2. Click create new project
3. Attempt to create a project using custom template.

### Expected behavior

Due to the worlds sdk now automatically including both the udonsharp and clientsim packages, the custom template should be deprecated and no longer available.

### Screenshots

![image](https://github.com/vrchat-community/creator-companion/assets/28989460/7cf121fb-19e9-4a1c-b5a0-6cf1fa77f6b2)
![image](https://github.com/vrchat-community/creator-companion/assets/28989460/02d8dce4-3ae6-4292-991f-192bb248e440)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.4

### OS

Windows 10

**Comment by orels1** [comment]
This should be fixed in the next release

**Comment by momo-the-monster** [comment]
Should be fixed now in [Creator Companion 2.1.5](https://vcc.docs.vrchat.com/news/release-2.1.5), thanks for reporting!
