### ISSUE TITLE
[BUG] Incorrect interpretation of `unity` field of package manifest and impossible to declare package compatible with both 2019 and 2022.

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#367]
### Describe the bug

According to [unity docs][unity-docs-manifest], the `unity` field of UPM package indicates minimum compatible unity version.

> Indicates the lowest Unity version the  package is compatible with.

[unity-docs-manifest]: https://docs.unity3d.com/2019.4/Documentation/Manual/upm-manifestPkg.html

### To Reproduce

1. Add my VCC repository for testing VCC bugs (https://anatawa12.github.io/vpm-repo-for-vcc-bug-testing)
2. Create Unity 2022 project with Unity Hub
3. Add the project to VCC with `Add existing project`
4. Try to add `The package with unity field with value 2019.4` to the project
5. Warning about unity version incompatibility is shown

### Expected behavior

Since `The package with unity field value 2019.4` declares compatible with Unity 2019.4 or later, the VCC should not warn about unity versions.

### Screenshots

<img width="829" alt="image" src="https://github.com/vrchat-community/creator-companion/assets/22656849/ccd0622a-34f5-4037-8983-df1a671d0a39">

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.5

### OS

Windows 11

### Additional context

I think VRChat want to declare VRCSDK compatible only with 2019.4 or 2022.3 so VCC interpret like this. 

However, current interpretation make community packages impossible to declare compatible with both 2019.4 and 2022.3 (and other versions).

In addition, many UPM package incorrectly will be detected as incompatible with installed unity versions. This can be problem when VRMConverterForVRChat by esperecyan start using newer UniVRM.

I worried about this problem 4 month ago so I already made issue suggests new VCC specific property for unity versions to solve this problem. Could you consider this issue?
- #311

**Comment by orels1** [comment]
We will remove the warning when adding a 2019 minimum version package to a 2022 project to follow Unity's guidelines better.

This will be done in the 2022-compatible VCC release. Thanks for the report!
