### ISSUE TITLE
[BUG] Adding large packages fails if downloading them takes longer than the default timeout

### ISSUE THREAD

**Issue by mahuvrc** [vrchat-community/creator-companion#372]
### Describe the bug

Often times github throttles download speeds of releases (at least for me). Because of this, packages in the 50+ mb range frequently fail to download with the error "One or more errors occurred. (A task was canceled.)" after about 2 minutes, perhaps due to an HttpClient timeout. (The default is 100 seconds, so that seems like it might just never have been configured.)

### To Reproduce

Add a large enough package to your project that it takes over 2 minutes to download. For example, poiyomi shaders 8.1.167 can take over 2 minutes to download from github for me due to how they shape their traffic: https://poiyomi.github.io/vpm/

It will time out if it takes too long to download

### Expected behavior

The package should be allowed to finish downloading. Ideally packages that are this large would show a progress bar during the download instead of just a spinner. Shaders and prefabs often times come with textures so these packages can get a little hefty. 

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.6

### OS

Windows 10

**Comment by orels1** [comment]
This should be fixed in VCC 2.2.x
