### ISSUE TITLE
[BUG] Could not download and install the VPM Package Resolver - you may be missing packages. Exception: The remote server returned an error: (404) Not Found.

### ISSUE THREAD

**Issue by Leli1024** [vrchat-community/creator-companion#375]
### Describe the bug

Each time I try to open a blank VRChat project I keep getting this error, this has been happening for a week

### To Reproduce

1. Download and open the blank template projects (I used Avatar template)

### Expected behavior

Expected Behavior: Expected VPM to install successfully

### Related Product

vpm-resolver (Package Resolver)

### Product Version

2.1.1

### OS

macOS / Linux

**Comment by orels1** [comment]
You should try again! This issue should be resolved now
