### ISSUE TITLE
[BUG] VCC stuck on Unity selection screen

### ISSUE THREAD

**Issue by Tails884** [vrchat-community/creator-companion#38]
**explain bug**.
After installing VCC, I get this screen and cannot operate.
Same screen after starting as administrator.

**How to reproduce
Install VCC
Startup

**Screenshots**.
![ugokanu](https://user-images.githubusercontent.com/120150711/206612164-ca39a6f5-55f1-4760-981c-204f2a355910.jpg)

**Desktop (please provide the following information):**
 - OS Windows 10 Pro
 - Version 21H2

**Add context**
Stops at the same screen after removing unity and unityHUB

Translated with www.DeepL.com/Translator (free version)

**Comment by orels1** [comment]
I would suggest to test the latest version, as well as try the "Rese\tart as Admin" mode, which can fix access issues with Unity installs.

**Comment by orels1** [comment]
This should be addressed in the VCC 2.0!
[Grab it from here](https://vrchat.com/download/vcc)
