### ISSUE TITLE
[BUG] `Click this link to start installation in Unity Hub` for Unity 2022.3.6f1 is not working 

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#384]
### Describe the bug

`Click this link to start installation in Unity Hub` for Unity 2022.3.6f1 is not working 

### To Reproduce

1. Open Settings page
2. Select Unity 2022
3. Click `Install Now` on the left of "No Recommended Version Set"
4. Click Install Unity
5. Select Click I have installed the Unity Hub
6. Unity installation failed with error (see #368 
7. Click `Install Manually`
8. Click `Click this link to start installation in Unity Hub`
9. Nothing happens

### Expected behavior

Unity Hub opens as we opened `unityhub://2022.3.6f1/b9e6e7e9fa2d` link

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.0

### OS

Windows 11

**Comment by slord399** [comment]
Seems to be "current unity version" page also using outdated link.
![SYl61ka](https://github.com/vrchat-community/creator-companion/assets/50810875/34160c33-82aa-43d3-bb1c-46bc16706afc)

**Comment by momo-the-monster** [comment]
Should be fixed in release 2.2.4.
