### ISSUE TITLE
[FEATURE] Please provide OpenBeta for VRChat Creator Companion

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#397]
**Is your feature request related to a problem? Please describe.**

Recently, VCC 2.2.0, 2.2.1, and 2.2.2 were released with some problems.
In my opinion, VCC 2.2.x is problematic because SDK 3.5.0 was not released, but VCC 2.2.x expects SDK 3.5.0.
In addition, I think VRChat believes in closed beta too much.

**Describe the solution you'd like**

To fix problems with VCC and SDK versions mismatch, I want OpenBeta releases for VCC.
If we have OpenBeta releases for VCC, we can investigate problems and report back to devs,　and prepare information for non-english users.

**Describe alternatives you've considered**

Possibly doing more closed beta but may not be suitable in this case.

**Additional contexts**

As I mentioned in [this Canny](https://feedback.vrchat.com/sdk-bug-reports/p/do-something-about-thinking-that-a-mere-3-hours-for-beta-testing-the-sdk-is-acce), 
VRChat declared VRChat will Increase Communication with Creators in December 2022.

I think OpenBeta releases are one of the ways to increase communication with creators, especially for tool authors.

**Comment by Sayamame-beans** [comment]
I am really wondering, has VCC been adequately tested internally?
I can't hide my shock that the ability to migrate a project from 2019 to 2022, which worked almost fine in 2.2.3, is now broken in 2.2.4 patch update. (See also: #434, #435, #436)

**Comment by orels1** [comment]
We are looking into options for this.
Currently the potential of providing a "Portable" installation of the VCC that stores and reads settings data from the folder it in in is something we're leaning toward. This will allow users to safely experiment with the Beta Creator Companion without affecting their main instance

**Comment by Sayamame-beans** [comment]
That sounds good.
It should be much better than finding problems after release.

**Comment by orels1** [comment]
Can confirm that we are going ahead with this solution.
We will most likely share final information on the [VRChat Forums' Creator Hub](https://ask.vrchat.com/c/creator-hub/announcements/71)

**Comment by orels1** [comment]
The first open beta is now available!
You can grab the 2.3.0 beta.1 here: https://github.com/vrchat-community/creator-companion/releases
