### ISSUE TITLE
[FEATURE] Warn if project folder is in VCC's application directory.

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#40]
**Is your feature request related to a problem? Please describe.**
Few hours ago, my friend updated VCC and he lost all him projects because he saved Projects in VCC's application directory.

**Describe the solution you'd like**
To avoid such situation in the future, I want VCC to warn if we were creating new project into or adding existing projects in VCC application directory.

**Describe alternatives you've considered**
N/A

**Additional context**
In his case, VCC is installed to `D:\VRChat Creator Companion` and project is in `D:\VRChat Creator Companion\Projects`.

He says `.minecraft` directory for Minecraft (in AppData and consists of both application file and user data) is frequently modified by users, so he thought VCC's application folder is also be one place for projects.

There may be more people who think application folder is place for projects than developers thought.

**Comment by anatawa12** [comment]
Recent VCC 2.0.x update breaks projects of at least four users due to lack of this. This is important for users.

- [Japanese Tweet by qfwk_vrc](https://twitter.com/qfwk_vrc/status/1634167097034162182?s=20)
- [Japanese Tweet by miyakon07VRC](https://twitter.com/miyakon07VRC/status/1634139302895468544?s=20)
- [Japanese Tweet by John_do_iwan](https://twitter.com/John_do_iwan/status/1634449978474266624?s=20)
- [Japanese Tweet by apkallu_qiwi](https://twitter.com/apkallu_qiwi/status/1634443671985848320?s=20)

**Comment by Sayamame-beans** [comment]
And one person said, "This is not general knowledge."
Since we are using an "SDK", it is doubtful that this logic will apply to us as developers, but I think it is still desirable to prevent accidents that can be prevented.
- [Japanese Tweet by tokiwailm](https://twitter.com/tokiwailm/status/1634508941299437569)

**Comment by Faxmashine** [comment]
The installer used to delete everything in the VCC's installation folder. This has been fixed, and it only deleted folders and DLLs it created itself. User-created folders and files should be safe.

We did not add a warning about adding user folders to the installation folder (yet).

**Comment by orels1** [comment]
Some in-progress screens that should help avoid these issues:



![Image](https://user-images.githubusercontent.com/3798928/234033976-04667366-d5a2-4ec5-a4d7-df15fa2404b8.png)



![Image](https://user-images.githubusercontent.com/3798928/234034114-3e596bea-f5a7-4d8d-9b27-e6fc50159cc7.png)

**Comment by orels1** [comment]
Project path validator will now also check against the VCC exe path


![Image](https://user-images.githubusercontent.com/3798928/234038046-c2683727-c683-4c89-b6ee-02812be04907.png)
