### ISSUE TITLE
[BUG] VCC installs VRCSDK 3.5.0 into Unity 2019 Project without warning if VRCSDK is updated by dependencies

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#404]
### Describe the bug

VCC installs VRCSDK 3.5.0 into Unity 2019 Project without warning if VRCSDK is updated by dependencies.

### To Reproduce

1. Create Unity 2019 project with VRCSDK 3.3.0 or earlier.
2. Try to package depends on VRCSDK 3.4.0 or later. \
   You can use The Package depends on SDK Worlds 3.4.0 in https://anatawa12.github.io/vpm-repo-for-vcc-bug-testing/ for testing.
3. Now VCC will upgrades VRCSDK 3.5.0 instead of 3.4.0

### Expected behavior

VCC upgrades VRCSDK to 3.4.0 for that project.

If the dependencies actually needs VRCSDK 3.5.0 / later, VCC should fail to install that package with Unity Version Mismatch Error.

### Screenshots

![Screenshot 2023-12-14 132046](https://github.com/vrchat-community/creator-companion/assets/22656849/376d03a8-06bc-45d9-bdf4-e9358b84731c)
![Screenshot 2023-12-14 132348](https://github.com/vrchat-community/creator-companion/assets/22656849/18d1a811-6aea-4b26-acf1-696810014e92)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.2

### OS

Windows 11

### Additional context

VCC should consider `unity` field during package resolution as my [vrc-get](https://github.com/anatawa12/vrc-get) does.

**Comment by orels1** [comment]
Available in VCC 2.2.4
