### ISSUE TITLE
[BUG] VPM Resolver will be added to projects without resolver during migration

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#407]
### Describe the bug

VPM Resolver will be added to projects without resolver during migration.

In my project, VPM Resolver is omitted and I'm using [another resolver](https://github.com/anatawa12/vrc-get-resolver) because VPM Resolver is a embedded package and vrc-get resolver is a git UPM package.
A friend also excludes VPM Resolver from their project (and uses another resolver) for some reasons.

### To Reproduce

1. create Unity 2019 project
2. remove VPM Resolver
3. Migrate the project to 2022
4. Now VPM Resolver is added

### Expected behavior

VPM resolver should not be added if VPM resolver is not on the package list

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.2

### OS

Windows 11

### Additional context

I think this is related to #406

**Comment by orels1** [comment]
Not related to #406. Similar to the Legacy SDK migration - the 2022 migration is also always adding a resolver, as it is desired in most cases.

We can adjust it to check before adding in the future though.

**Comment by orels1** [comment]
Available in VCC 2.2.4
