### ISSUE TITLE
[BUG] migrate Legacy Project will install incompatible version of packages

### ISSUE THREAD

**Issue by Sayamame-beans** [vrchat-community/creator-companion#410]
### Describe the bug

If we migrate Legacy Projects, VCC will install SDK 3.5.0(or 3.5.0-beta.1) and Package Resolver Tool 0.1.27, even though the project unity version is 2019.4.31f1.
This leads destroy the project.

### To Reproduce

1. Open VCC
2. Do "Add Existing Project" and add Legacy project
3. Click "Upgrade SDK"
4. Migrate non-VCC to VCC
5. Click "Manage Project"
6. SDK is 3.5.0(or 3.5.0-beta.1) and Package Resolver Tool is 0.1.27

### Expected behavior

Install SDK 3.4.2 and Package Resolver Tool 0.1.26. (Latest version for Unity 2019.4.31f1)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.3

### OS

Windows 10

### Additional context

I think VCC is not checking the unity field when migrating legacy projects.
I'm not tested this on VPMCLI, but I suspect it also have the same problem.

**Comment by momo-the-monster** [comment]
Should be fixed in release 2.2.4.
