### ISSUE TITLE
[BUG] If we add package using + button, unity version compatibility is not considered

### ISSUE THREAD

**Issue by Sayamame-beans** [vrchat-community/creator-companion#414]
### Describe the bug

For example, when we add SDK with + button to Unity2019 project, VCC tries to import 3.5.0 (for Unity2022 latest), and migration dialog is showed up.
This also happens for community packages, so it confuses users.

VCC should check the unity version field and choose as new version as possible that is compatible with the project's unity version.

### To Reproduce

For easily repro,
1. Create Unity 2019 project with VCC
2. Remove World/Avatar SDK Package
3. Add World/Avatar SDK using + button

### Expected behavior

Import SDK 3.4.2 (for Unity2019 latest)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.3

### OS

Windows 10

**Comment by orels1** [comment]
Available in VCC 2.2.4
