### ISSUE TITLE
[BUG] Creator Companion stuck on white screen at launch

### ISSUE THREAD

**Issue by RealRobbieMC** [vrchat-community/creator-companion#417]
### Describe the bug

Hello. I just installed the creator companion, however, whenver it opens it stays stuck on a white screen and wont load anything.

### To Reproduce

1. Go to the VRChat website and download the Creator Companion
2. Follow the install directions
3. Open Creator Companion

### Expected behavior

Expected to have a loading screen of some kind

### Screenshots

![Screenshot (54)](https://github.com/vrchat-community/creator-companion/assets/155774514/b3220171-81e1-4bc3-8925-1ebd3eba0eea)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.3

### OS

Windows 10

**Comment by anatawa12** [comment]
Did you uninstalled Microsoft Edge? If so, try installing Microsoft Edge. WebView2 is based on Microsoft Edge so if you uninstalled Microsoft Edge, VCC does not work well.

If not, your VCC configuration file might be corrupted. Could you try renaming config file? it's at `%LOCALAPPDATA%\VRChatCreatorCompanion\config.json`. try renaming to `config.bak.json`

**Comment by Moonboy65** [comment]
got the same error just now, i have Edge installed too and updated, still getting white screen, I don't have a config file either

**Comment by anatawa12** [comment]
Could you share log file of VCC?  They are in `%LOCALAPPDATA%\VRChatCreatorCompanion\Logs` directory (folder)

**Comment by Moonboy65** [comment]
it's fine now, seems like a quick PC restart fixed it

**Comment by orels1** [comment]
I will close this issue is this is already solved.
It might've also been an occupied API port situation, which has been solved with VCC 2.2.4

If you come across this issue again - feel free to make a new port!

**Comment by MidoriChanPL** [comment]
Hey! I’m getting the same exact issue, everything was working fine and when I wanted to go ahead and work on some stuff this thing happened. I already tried everything there was available on any forums. Reinstalling, restarting my pc multiple times, deleting the settings.json, changed the path to the preferred folders. Completely swiped it from my pc and reinstalled it, reinstalled edge and just tried everything I could but still, nothing seems to work

**Comment by Mehidden** [comment]
Same issue, after windows 11 update :/(I'm betting the most recent windows update broke it)

**Comment by J1G5AW420** [comment]
> ### This message is from creation companion channel in Discord:
> If your VCC is not loading correctly, try uninstalling the following updates: KB5066835 and KB5065789. If your machine is older, you may also need to uninstall KB5066131. As an alternative from the community, you can try using [ALCOM](https://vrc-get.anatawa12.com/alcom/)
> 
> For the time being, you can also launch the project directly from Unity Hub. To uninstall the updates, open an elevated Command Prompt (run as administrator) and execute the following commands. Remember to restart Windows after applying each action. (Thanks to Myrkur for the information.)
> 
> wusa /uninstall /kb:5066835
> 
> wusa /uninstall /kb:5065789
> 
> wusa /uninstall /kb:5066131 (For older machine)




I unstalled to the top 2 that are listed here and now its working, Thank you @DEV-MCWEBPANEL for posting this, it does seem like the most recent updates for windows broke it. So people can either go through unity hub or just uninstall at least the top 2 and it should work.
