### ISSUE TITLE
[BUG] unable to load. 

### ISSUE THREAD

**Issue by OhItsNeko** [vrchat-community/creator-companion#418]
### Describe the bug

so last night i was able to load the vcc but for some reason today im not even able to open the application and i dont even know what happened cause all i did was upload a avi last night. so help please.

### To Reproduce

n/a

### Expected behavior

to open the application and load up like normal.

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.3

### OS

Windows 11

**Comment by DragonOfEmpire** [comment]
Same I also have the same issue as well too. Im not able to open the vcc application either.

**Comment by mauga** [comment]
The same for me. Log file contains only 

`2024-01-07 17:10:57.238 +01:00 [INF] VRCLibLogger Writing logs to C:\Users\Utente\AppData\Local\VRChatCreatorCompanion\Logs\20240107T171057-c6f1a855f1be47239f49eef1256c32f8-log.txt`

Just two days ago worked fine.
I've tried: reinstall app/remove and reistall app/delete config dir/delete config dir and project dir

I've no clue why not working and find no info on way to diagnose or how increase log verbosity.

**Comment by orels1** [comment]
On Windows 11 I would recommend trying the following:

- Open settings
- Go to Apps -> Installed Apps -> System Components
- Click the 3 dots menu on Xbox Game Bar -> Advanced Options
- Click Terminate
- See if VCC launches

If VCC starts - you can set Xbox Game Bar to never launch by selecting "Never" in the settings there
![image](https://github.com/vrchat-community/creator-companion/assets/3798928/7f496e4a-5fb6-4b9b-b214-3ee7f3b95c75)

If VCC still doesn't start - then it is probably something else, but we have some fixes for the Xbox Game Bar issue and overall startup issues in the works for next release

**Comment by orels1** [comment]
This should be addressed in VCC 2.2.4, you can download it here: https://vrcpm.vrchat.cloud/vcc/Builds/2.2.4/VRChat_CreatorCompanion_Setup_2.2.4.exe
If you're still experiencing this issue, please create a new report
