### ISSUE TITLE
[ENHANCEMENT] Pixelated app icon

### ISSUE THREAD

**Issue by Faxmashine** [vrchat-community/creator-companion#42]
The icon's pixelated!

**To Reproduce**
1. Open the VCC (web version)

**Expected behavior**
Look all smooth and good and stuff

**Screenshots**
Left: old VCC, right: web version
![Discord_u33LclOuE3](https://user-images.githubusercontent.com/117199600/207997942-512a87fa-12cf-45e3-bb23-d9d81bceb395.png)

**Desktop :**
 - OS: Windows 10
 - Version: Like, the newest

**Additional context**
Something something aliasing
Happy Holidays

**Comment by orels1** [comment]
This has been improved when we added portable beta builds
![image](https://github.com/user-attachments/assets/5a74d79f-c339-479f-9be0-d895d9e61d3f)
![image](https://github.com/user-attachments/assets/b2b1920e-b8ef-4f25-9f58-b976d8c13c19)
