### ISSUE TITLE
[BUG] Attempting to add a repository that is already added results in an unclear error

### ISSUE THREAD

**Issue by bdunderscore** [vrchat-community/creator-companion#424]
### Describe the bug

Attempting to add a repository that is already added (and possibly disabled) results in an unclear error. While the error points users to logs, and the logs do say that the repo is already added, and there's even a message which displays behind the modal (disappearing after a few seconds) saying the repo is already added... it seems that many users don't understand what the error means and give up.

I've helped four people with this just today, so this is a fairly widespread issue, particularly for folks who don't have a good grasp on English.

### To Reproduce

1. Add a user VPM repository
2. Add it again

### Expected behavior

If the repository is disabled, enable it. Otherwise, just close the add repo window without doing anything (or display a clearly successful-looking message saying that the repo was already there).

### Screenshots

![image](https://github.com/vrchat-community/creator-companion/assets/64174065/c9ab8fa8-bffb-4034-8e78-17dc3d67d9cd)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.3

### OS

Windows 11

**Comment by orels1** [comment]
This is going to be addressed in 2.3.0 release and included in 2.3.0 Beta 2

**Comment by orels1** [comment]
The fix for this is available in 2.3.0 Beta 2, you can download it here: https://github.com/vrchat-community/creator-companion/releases/download/2.3.0-beta.2/web_vcc_2.3.0-beta.2_Release_Portable.zip
