### ISSUE TITLE
[BUG] VCC 

### ISSUE THREAD

**Issue by emmasylvia** [vrchat-community/creator-companion#427]
### Describe the bug

I manually downloaded the version I needed cuz the VCC did not and it kept saying Invalid version format when it is the exact same version that was listed as what VR chat was using.

### To Reproduce

1.Download Unity hub 2.Go to the vcc 3.Press I already have Unity and then click on the file.

### Expected behavior

it will say Invalid version format

### Screenshots

![nhgs](https://github.com/vrchat-community/creator-companion/assets/114593216/41c8a295-4e94-43b2-99b9-26dda396731c)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2022.3.6f1.

### OS

Windows 10

### Additional context

has happened a lot to me

**Comment by anatawa12** [comment]
What you have to set on Add unity Editor is path to unity editor, not path to unity hub or unity hub installer. It looks you're setting path to unity hub installer.

**Comment by orels1** [comment]
As pointed out above - you need to install the Unity Hub first and then either let the VCC find/install the editor for you. (Or point to the actual `Unity.exe` after you install it through Unity Hub yourself).
