### ISSUE TITLE
[BUG] [Regression?] Can't add multiple projects

### ISSUE THREAD

**Issue by Faxmashine** [vrchat-community/creator-companion#43]
In the old VCC, it was possible to select the parent directory of Unity projects. This allowed users to add multiple projects if they all shared the same parent directory.
This is no longer possible in the new React version, and users need to add projects one by one.

@orels1 offers the following workaround:
> also you can copy all your projects over quickly by just opening the settings.jsons for both
> and copy pasting the list of them

**Comment by hyblocker** [comment]
It might make more sense to also allow multi-select on the folder selection dialog, as it's more intuitive more most users than selecting a parent directory. Currently the folder dialog doesn't allow one to select multiple directories.

**Comment by momo-the-monster** [comment]
Fixed in next release!
