### ISSUE TITLE
[BUG] Audio Link will be added to projects without Audio Link during unity 2022 migration

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#434]
### Describe the bug

Audio Link will be added to projects without Audio Link during unity 2022 migration

Exactly same issue as #407 with different package

### To Reproduce

1. create avatars 2019 project
2. migrate the project

### Expected behavior

Packages not installed before migration must not be installed after migration (unless it's new dependencies of a packages)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.4

### OS

Windows 11

**Comment by anatawa12** [comment]
In addition, This warning is shown even if we don't have any (custom) shaders with audiolink
<img width="788" alt="image" src="https://github.com/vrchat-community/creator-companion/assets/22656849/960b806e-0f57-4011-b297-d8d633c225ec">

**Comment by orels1** [comment]
Hmm, odd.
There is logic in place to upgrade pre-1.x AL to 1.x AL if it was already in the project, to avoid it requesting to install UdonSharp for people who were using pre 3.4.x SDKs before the migration.

Was able to reproduce, so I'll look into why a project without audio link might report that it has sub 1.x audiolink installed, thanks for the report 👍 

Second issue is with AudioLink itself, its seems to fire every single time no matter if you have any shaders in the project or not. Might be worth creating an issue on the AudioLink repository if you think its a bug.

**Comment by orels1** [comment]
This is addressed in VCC 2.2.5 that was just released
