### ISSUE TITLE
[BUG] Migrating Avatars project removes VRCSDK

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#435]
### Describe the bug

Migrating Avatars project removes VRCSDK

### To Reproduce

1. Create Avatars 2019 project
2. Click Migate to 2022 (both in place and copy)

### Expected behavior

VRCSDK Avatars 3.5.1 is installed

**Actual Behavior**

None of VRCSDK is installed

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.4

### OS

Windows 11

### Additional context

My friend on Windows 10 reproduced this issue.

**Comment by anatawa12** [comment]
It looks migrating worlds project doesn't cause this issue.

**Comment by orels1** [comment]
This is addressed in VCC 2.2.5 that was just released
