### ISSUE TITLE
[BUG] Migrating a copy will not migrate vpm resolver to 0.1.28

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#436]
### Describe the bug

Migrating a copy will not migrate vpm resolver to 0.1.28

### To Reproduce

1. Create Unity 2019 project (worlds or avatars)
2. Migrate the project a Copy (not inplace)
3. resolver 0.1.26 is still installed

### Expected behavior

resolver is upgraded to 0.1.28

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.4

### OS

Windows 11

**Comment by orels1** [comment]
This is addressed in VCC 2.2.5 that was just released
