### ISSUE TITLE
[BUG] removing LegacyFolders by GUID is not working

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#439]
### Describe the bug

Removing legacyFolders by GUID is not working

### To Reproduce

1. create or add unity project
2. import this unitypackage to the project: https://github.com/anatawa12/vpm-repo-for-vcc-bug-testing/blob/main/folder-removed-by-legacy-folder-with-guid.unitypackage
  this unitypackage adds folder with GUID `08a9eae68bc34792ba38da0c96210685`
3. add this repository: https://anatawa12.github.io/vpm-repo-for-vcc-bug-testing/
4. Add `Legacy Folder with GUID(08a9eae68bc34792ba38da0c96210685)` to the project

### Expected behavior

`Assets/RemovedWithGuid` folder (which is added by step 2) should be removed

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.5

### OS

Windows 10

**Comment by orels1** [comment]
This behaviour has been adjusted in the 2.3.0 open beta, you can get it here https://github.com/vrchat-community/creator-companion/releases/tag/2.3.0

We also updated relevant documentation to explain how exactly this is supposed to work: https://vcc.docs.vrchat.com/vpm/packages/#vpm-manifest-additions

**Comment by orels1** [comment]
This has been released to live with version 2.3.0: https://vrcpm.vrchat.cloud/vcc/Builds/2.3.0/VRChat_CreatorCompanion_Setup_2.3.0.exe
