### ISSUE TITLE
[FEATURE] Show project status on project screen

### ISSUE THREAD

**Issue by Faxmashine** [vrchat-community/creator-companion#44]
**Is your feature request related to a problem? Please describe.**
The old VCC showed you if a project needed migration *before* you opened the project.
![CreatorCompanion_PYmvcI1VGe](https://user-images.githubusercontent.com/117199600/208001068-fd1ce380-4afb-41a2-8c47-0fe4ae70aa62.png)

The new web app only shows this information on the package management screen. So it's easy to open a project without realizing that it requires migration.

**Describe the solution you'd like**
A little icon ℹ⬆ indicating if a project is
- A legacy project
- A VCC project
- Something else

**Comment by DrBlackRat** [comment]
Maybe also consider using the same or a similar icon and placement for indicating when ever a Project has Packages which need Updates as I've described in #66.

**Comment by orels1** [comment]
Addressed in the next release
