### ISSUE TITLE
[BUG] [2.3.0 beta] remote repository cache is not copied to portable user data folder

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#448]
### Describe the bug

remote repository cache is not copied to portable user data folder, shared with live instead.

I think it's better to detect if it's local cache, copy local repository cache and fix settings.json is good.

### To Reproduce

1. add some community repository in stable vcc;
2. launch beta vcc and click copy data 

### Expected behavior

remote repository cache is copied to portable user data folder and not shared with stable vcc.

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.3.0 beta.1

### OS

Windows 11

**Comment by orels1** [comment]
This is being addressed for 2.3.0 Beta 2 release

**Comment by orels1** [comment]
The fix for this is now shipped in the 2.3.0 Beta 2 release, you can download it here: https://github.com/vrchat-community/creator-companion/releases/download/2.3.0-beta.2/web_vcc_2.3.0-beta.2_Release_Portable.zip
