### ISSUE TITLE
[BUG] [UX] Folder dialogs should be shown as a "dialog" rather than a window

### ISSUE THREAD

**Issue by hyblocker** [vrchat-community/creator-companion#45]
The folder selection dialogs in the VCC should be a dialog, which prevents the user from clicking the main VCC window while the folder selection dialogs is visible, forcing the user to either close the dialog or select a folder. The app itself ignores user input in such a state, and opening the dialog as a "dialog window" would further enforce this.

**Comment by orels1** [comment]
While we did not directly address this, we're currently satisfied with how our dialogs are handled
