### ISSUE TITLE
[BUG] "Project Resolve Needed" Resolve action doesn't do anything

### ISSUE THREAD

**Issue by hai-vr** [vrchat-community/creator-companion#450]
### Describe the bug

"Project Resolve Needed" Resolve doesn't do anything.

### To Reproduce

- Unknown starting conditions.
- Click "Manage Project".
- The "Project Resolve Needed" shows up.
- Click "Resolve".
- Go back a page.
- Click "Manage Project" on the same project.
- The "Project Resolve Needed" shows up.

### Expected behavior

- The "Project Resolve Needed" should popup not show up again.
- This persists across restarts.

### Screenshots

https://discord.com/channels/189511567539306508/449386885299830794/1221395535253082183

### Related Product

VCC (VRChat Creator Companion)

### Product Version

web_vcc_2.3.0-rc.1_Release_Portable

### OS

Windows 10

### Additional context

Please provide information on exactly what files are needed to troubleshoot this issue. I'm not gonna upload my entire avatar project.

**Comment by orels1** [comment]
@hai-vr can you provide a logfile when that happens?

If the project resolve was in-progress while you left the page - the consecutive check for resolve status will (correctly) detect that project is still unresolved.
However, there is logic in place that should reopen the resolve modal to the same in-progress state, which does not seem to be happening for you.

**Comment by hai-vr** [comment]
[20240328T070240-7432d501ad5544c39b644df093df1007-log.txt](https://github.com/vrchat-community/creator-companion/files/14784631/20240328T070240-7432d501ad5544c39b644df093df1007-log.txt)

**Comment by orels1** [comment]
Thanks for the log!

I am so far unable to replicate with the public repositories you have listed so I'll need some more input to try and address this. Something about that project is making it unhappy.

Resolve popup checks if the packages on disk exist and match the manifest, so the following info would be appreciated:

- `vpm-manifest.json`
- list of folders in the `Packages` folder (screenshot works)
- If you do not want to share those - I would ask to check if the list of packages in the manifest's `locked` list matches the folders present on disk (and if the versions match)
- If any of this changes post resolve

What is supposed to happen:

- The repos are scanned for package availability
- If all packages are downloadable - the resolve will start
- If not all the packages are downloadable - a list of resolvable/unresolvable packages will show up offering a couple ways to proceed

Seems like for you it aborts immediately on the start of the process, which almost makes me feel like the resolve function is not finding anything that's missing and exits early, so I'm trying to track down why

**Comment by orels1** [comment]
One more thing that I would really appreciate is if you could do the following:

- Go to the offending project's page
- Press F12
- Select the Network tab in the DevTools window that shows up
- Press Ctrl+R to refresh the page
- In the popup that shows up - click "Resolve"
- Find the `canResolve?projectId=<guid>` request in the list, click on it, select the "Preview" tab and share the data shown, e.g.
- 
![image](https://github.com/vrchat-community/creator-companion/assets/3798928/00f1a859-cbd4-4bda-9a9c-94b9a087ce0c)

- Find the `resolve` request in the list below the `canResolve` request, do the same as for the previous one, e.g.

![image](https://github.com/vrchat-community/creator-companion/assets/3798928/0fefc6bb-9728-4cd1-95fc-1485c025a134)

- Finally, find the following `resolveNeeded` request and do the same, e.g.

![image](https://github.com/vrchat-community/creator-companion/assets/3798928/4d6ad8fb-21e3-4fdf-af44-564eed39024a)

Alternatively, you can privately send an HAR file to `orels@vrchat.com` so I can inspect the request tree directly.

If you feel comfortable with that, you would need to do the following

- Go to the offending project's page
- Press F12
- Go to the Network tab
- Press Ctrl+R
- Right click on the list of requests and select "Save all as HAR with content"
- Send me the said HAR file

This could potentially shed some light on why you're getting in such a loop

**Comment by orels1** [comment]
A tentative fix for this is shipped in 2.3.0 Beta 2 release, you can download it here: https://github.com/vrchat-community/creator-companion/releases/download/2.3.0-beta.2/web_vcc_2.3.0-beta.2_Release_Portable.zip

If you still encounter the issue in that update, I would appreciate if you could send me the information requested earlier

**Comment by orels1** [comment]
Using a repro provided by @anatawa12 in #460 this seems to be related to a manifest file that contains conflicting versions - e.g. if you force install some package that breaks the dependency rules.

The logs and visual behaviour matches between these cases and it should be addressed in next release

**Comment by orels1** [comment]
This has been released to live with version 2.3.0: https://vrcpm.vrchat.cloud/vcc/Builds/2.3.0/VRChat_CreatorCompanion_Setup_2.3.0.exe
