### ISSUE TITLE
[BUG] "Project Resolve Needed" modal persists across opening different projects if it was not closed.

### ISSUE THREAD

**Issue by hai-vr** [vrchat-community/creator-companion#451]
### Describe the bug

"Project Resolve Needed" modal persists across "Manage Project" on different projects if it was not closed.

### To Reproduce

- Click "Manage Project" on a project that triggers the "Project Resolve Needed" modal.
- Do not close the modal, go back using the right-hand arrow icon at the top left next to the project name.
- Click "Manage Project" on a project that was confirmed not to trigger the "Project Resolve Needed" modal.
- The "Project Resolve Needed" modal appears

### Expected behavior

The "Project Resolve Needed" modal should not appear

### Related Product

VCC (VRChat Creator Companion)

### Product Version

web_vcc_2.3.0-rc.1_Release_Portable

### OS

Windows 10

**Comment by orels1** [comment]
This is being addressed for 2.3.0 Beta 2 release

**Comment by orels1** [comment]
The fix for this is shipped in the 2.3.0 Beta 2 release, you can download it here: https://github.com/vrchat-community/creator-companion/releases/download/2.3.0-beta.2/web_vcc_2.3.0-beta.2_Release_Portable.zip
