### ISSUE TITLE
[BUG] `vpm list unity` can't list unity editors on macOS

### ISSUE THREAD

**Issue by kurotu** [vrchat-community/creator-companion#46]
**Describe the bug**
`vpm list unity` can't list unity editors on macOS.

VPM CLI version: 0.1.13

**To Reproduce**
1. Install Unity Hub manually.
2. Install Unity 2019.4.31f1 in Unity Hub.
3. Quit Unity Hub.
4. Execute `vpm list unity`.
5. Found no unity editors:
```
[02:02:50 INF] Found 0 Unity Installations.
```

**Expected behavior**
`vpm list unity` lists installed unity editors.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 11.7.2

**Additional context**
When Unity Hub is already running, `vpm list unity` successfully lists installed unity editors.

```
[02:06:02 INF] Found 1 Unity Installations.
[02:06:02 INF] /Applications/Unity/Hub/Editor/2019.4.31f1/Unity.app/Contents/MacOS/Unity
```

However the problem occurs just after Unity Hub is started. So I feel it's timing-dependent problem.

**Comment by kurotu** [comment]
Unity Hub 3.4.1 successfully lists unity editors even if Unity Hub is not already running.

```shell
$ /Applications/Unity\ Hub.app/Contents/MacOS/Unity\ Hub -- --headless editors -i
2019.4.31f1 , installed at /Applications/Unity/Hub/Editor/2019.4.31f1/Unity.app
```

**Comment by Faxmashine** [comment]
Thank you for your report!
This appears to be a duplicate. Please submit any additional information to https://github.com/vrchat-community/creator-companion/issues/28
