### ISSUE TITLE
[BUG] [VCC-WEB] settings.json button does nothing

### ISSUE THREAD

**Issue by Codel1417** [vrchat-community/creator-companion#47]
**Describe the bug**
the settings.json button does not do anything.

**To Reproduce**
Open VCC
Click Settings
Click settings.json

**Expected behavior**
The File Explorer opens showing the settings.json file.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Additional context**

**Comment by momo-the-monster** [comment]
We haven't been able to reproduce this, can you provide any other context? What happens if you double-click on a .json file from the Windows Explorer?

**Comment by Codel1417** [comment]
When I double click it opens in VSCode as that's my default for json files

**Comment by orels1** [comment]
This should be addressed in the VCC 2.0, the settings.json button now opens the containing folder to avoid potential issues with associated applications.
[Grab it from here](https://vrchat.com/download/vcc)
