### ISSUE TITLE
[BUG] VCC 2.3.0-beta.3 Manual install trys to install the wrong version of Unity

### ISSUE THREAD

**Issue by Saberpeep** [vrchat-community/creator-companion#471]
### Describe the bug

So I just tried out the latest beta VCC and after spending a while downloading the Unity installer, it got stuck on the installing Unity step (may be a bug in of itself). So I clicked the manual install button, and then clicked the "Click this link to start installation in Unity hub" link only for Unity hub to pop up and tell me "Unity 2022.3.6f1 is already installed". That's supposed to be Unity 2022.3.22f1. Unity hub shows no signs of ever having downloaded Unity 2022.3.22f1.

### To Reproduce

1. Open web_vcc_2.3.0-beta.3_Release_Portable.
2. Click the button in the banner at the top to install the latest unity.
3. Wait for the installer to download.
4. Once it gets to the installing step, click "Having trouble try manually".
5. Click the "Click this link to start installation in Unity hub" link.
6. Unity hub opens and tells me that "Unity 2022.3.6f1 is already installed" (Unity hub shows no signs of ever having downloaded 2022.3.22f1).

### Expected behavior

Unity Hub should open and begin installing 2022.3.22f1

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.3.0-beta.3

### OS

Windows 11

**Comment by orels1** [comment]
Thanks for the report! We will address this for the full release

**Comment by orels1** [comment]
This has been released to live with version 2.3.0: https://vrcpm.vrchat.cloud/vcc/Builds/2.3.0/VRChat_CreatorCompanion_Setup_2.3.0.exe
