### ISSUE TITLE
[BUG] VRC Quick Launcher crashes when I click "browse" on the VRChat path dropdown

### ISSUE THREAD

**Issue by bdunderscore** [vrchat-community/creator-companion#476]
### Describe the bug

My VRC quick launcher looks like this:

![image](https://github.com/vrchat-community/creator-companion/assets/64174065/a9a619fe-9c4c-4742-b2fa-7db88c13239e)

If I click browse, it immediately crashes with no error message.

### To Reproduce

1. Click browse.
2. Crash.

### Expected behavior

Don't crash. Or, at least show an error or a pointer to logs.

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.5

### OS

Windows 11

### Additional context

Clearing paths and install profiles does not resolve the issue. It's unclear where the logs - if any - are.

**Comment by bdunderscore** [comment]
It looks like the directory `\` is being passed as the OpenFileDialog initial directory, which causes an uncaught exception to be raised at `OpenFileDialog.ShowDialog()`

**Comment by bdunderscore** [comment]
![image](https://github.com/vrchat-community/creator-companion/assets/64174065/e3a4881e-2cfa-4b8e-8012-6d902f45af2c)
![image](https://github.com/vrchat-community/creator-companion/assets/64174065/2d5b9a56-cdc2-4222-8d10-62cd779d70c6)

It appears that if the InstallLocation field in the uninstall registry entry for VRChat contains an empty string, the quick launcher will crash on browse.

**Comment by orels1** [comment]
@JordoVR for awareness

**Comment by orels1** [comment]
This is released as a part of 2.3.2 It is accessible via auto-update and the VCC releases page here: 
https://vcc.docs.vrchat.com/news/release-2.3.2

The public announcements will be posted later in the day
