### ISSUE TITLE
[BUG] VCC: Protocol links with headers not working since v2.3.0

### ISSUE THREAD

**Issue by Dreadrith** [vrchat-community/creator-companion#486]
### Describe the bug

Note: Adding a listing to VCC by manually inputting the URL and headers works fine.

Using protocol links with the format `vcc://vpm/addRepo?url=<LISTNG_URL>&headers[]=<HEADER_KEY>:<HEADER_VALUE>`
Versions **below** v2.3.0 are able to process it and add the listing correctly.
Versions **equal or above** v2.3.0 are not processing the same links correctly and fail to get the listing. I can only assume it's because it's not processing or using the headers correctly.
I'm not sure if it's because the format changed or something broke.

### To Reproduce

Here's a short link that leads to a protocol link with the required headers: https://dreadrith.com/vcc-test
Using VCC version 2.3.0 or above, click the link.

### Expected behavior

VCC successfully adds the listing.

### Screenshots

Failed listing addition through the protocol link on v2.3.0
![image](https://github.com/vrchat-community/creator-companion/assets/73959477/44da554f-5048-4ca0-aac2-540f64671ed2)

Successful listing addition through the protocol link on v2.2.5
![image](https://github.com/vrchat-community/creator-companion/assets/73959477/68456ac8-453b-4145-af72-b35728ccfc84)

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.3.0+

### OS

Windows 10

### Additional context

On that note, v2.3.1 seems to also exhibit some bugs with protocol links without headers. It sometimes closes itself, or blinks, and/or opens another instance of VCC.

**Comment by orels1** [comment]
VCC used to simply check if the port was already taken to perform deep link forwarding, but this was changed since the ports were made fully dynamic in 2.3.0 (to avoid issues with port collisions with things like Xbox GameBar and so on).

Instead it is now using MDNS to discover the previously running instances, seems like this issue is a result of that changeover.

**Comment by orels1** [comment]
The fix for this is going to be available in the next release

**Comment by orels1** [comment]
This is released as a part of 2.3.2 It is accessible via auto-update and the VCC releases page here: 
https://vcc.docs.vrchat.com/news/release-2.3.2

The public announcements will be posted later in the day
