### ISSUE TITLE
[BUG] VCC won't convert project from 2019.4.31f1 to 2022.3.22f1

### ISSUE THREAD

**Issue by SourceTheProto** [vrchat-community/creator-companion#487]
### Describe the bug

I was trying to convert one of my older projects to the newest unity version, however it fails almost instantly, giving the error message "Trying to Check Changes for an unsupported project, you should not have gotten this far!" seeming to even fail before it starts the migration according to the logs
![Screenshot 2024-05-20 200034](https://github.com/vrchat-community/creator-companion/assets/136466583/66d3c48b-8da1-4340-9401-6ab34cae7097)

Also, a weird detail that may be causing the issue is that VCC reports the project type as unknown, although I don't know why it would be labeled as such
![Screenshot 2024-05-20 200603](https://github.com/vrchat-community/creator-companion/assets/136466583/55522e76-c1d4-4a83-bc51-5382eda0e022)

### To Reproduce

1. Click the Unity version upgrade button on the project
2. Select 2022.3.22f1 as the version to migrate to
3. Click the migrate button, then "Migrate in-place" when the confirmation dialogue appears
4. Errors show saying migration failed

### Expected behavior

I've previously upgraded projects from 2019 to 2022.3.6f1 before, but the only project i've upgraded to 2022.3.22f1 successfully before this was one that was already on 2022.3.6f1, and I had no issues with that one.

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.3.1

### OS

Windows 10

### Additional context

I would just like to clarify that I did try googling first to no avail, and the weird project type and error message seemed appropriate to post here.

**Comment by SourceTheProto** [comment]
Oh yeah it does appear to not have the SDK packages installed somehow, it was supposed to be an avatar; here are the screenshots of the packages folder and the manage project page:
![packages](https://github.com/vrchat-community/creator-companion/assets/136466583/dd6df09a-d6fb-4718-a0ff-96bb99f984d0)
![manage](https://github.com/vrchat-community/creator-companion/assets/136466583/124bf56d-9769-4b56-8050-cf6ded0ef6ea)

I re-added the packages, then opened the project just to make sure they were fully installed, closed the project, and then attempted the migration again, but it failed again. Although I did discover that it seems to be removing the SDK packages as a part of the migration and then failing on something else, and leaving them like that, as it notes that in the logs and the packages are gone again.
![logs post migration](https://github.com/vrchat-community/creator-companion/assets/136466583/f119c93a-54ad-4a76-bf55-768d79b8d4d1)

**Comment by orels1** [comment]
Interesting, I wonder why its getting stuck on that file 🤔 
You can try removing it temporarily and see if it migrates? Not sure why it would get locked

**Comment by SourceTheProto** [comment]
Oh that actually worked! It just regenerated the file on its own and it went through with the process, thank you for that!

**Comment by orels1** [comment]
I think I'm going to close out this issue then. I think the most we can do here is improve documentation / error messages, but I don't think this is a bug in the VCC code itself. Thoughts @Faxmashine ?

**Comment by everyt** [comment]
I just encountered this bug, but the error message was too vague/abstract.
