### ISSUE TITLE
[FEATURE] [VCC-WEB] Page for managing repos

### ISSUE THREAD

**Issue by Codel1417** [vrchat-community/creator-companion#49]
A tab should exist to manage custom and built in repos. Similar to the Project tab. Here the user can add their own repos AND disable built in ones like the curated list.

**Comment by orels1** [comment]
This is planned to be implemented after initial release of the VCC-web

**Comment by orels1** [comment]
I'm going to close this, as the relevant work has been done as a part of https://github.com/vrchat-community/creator-companion/issues/205
