### ISSUE TITLE
[BUG} "Building and testing on this platform is not supported" for Android, and VRCCore-Editor.dll is not allowed

### ISSUE THREAD

**Issue by 3dimka** [vrchat-community/creator-companion#498]
I've been struggling with Android platform for my world project.
I'm using latest Unity and VR Chat CC, windows 10 pro.

I installed recommended by VR CHAT CC unity 2022.3.22f1. It has Android platform fully configured and compiling without errors on a default Unity Android project.

But an empty world created by the VR Chat CC, while works for Windows platform, doesn't build for Android.
The SDK Control panel says "Building and testing on this platform is not supported" when I switch to Android, so I cannot even start the build.
And if I build in Unity I'm getting the following build error:

ArgumentException: The Assembly UnityEditor.CoreModule is referenced by VRCCore-Editor ('Packages/com.vrchat.base/Runtime/VRCSDK/Plugins/VRCCore-Editor.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary2[TKey,TValue] cache, UnityEditor.BuildTarget target, UnityEditor.ScriptingImplementation scriptingImplementation) (at <80a8ce1980c648dca8e68f0d8aa3b930>:0)

<img width="892" alt="vrchat_world_android_build_problem" src="https://github.com/vrchat-community/creator-companion/assets/47431444/3e6fa652-66b0-444f-b2af-a791e9141a35">

**Comment by orels1** [comment]
Hey!
That is expected. You can only build and upload on android, since VRChat doesn't support local android / quest testing. You would need to upload a new build using the buttons at the bottom and then load it up on your mobile device / quest.

**Comment by 3dimka** [comment]
> Hey! That is expected. You can only build and upload on android, since VRChat doesn't support local android / quest testing. You would need to upload a new build using the buttons at the bottom and then load it up on your mobile device / quest.

I see, thanks. 
I've entered the world info and that unblocked the android build/upload button. 
I then uploaded the world and was able to open it on Quest.

Does this mean that there's no way of debugging the android quest world in unity?

**Comment by orels1** [comment]
Unfortunately, outside of regular play mode testing using ClientSim - there isn't really support for testing android specific things.

Most people just have a separate world ID they use just for testing android content and make a new upload whenever they change something

**Comment by orels1** [comment]
I will close this issue as this is not a Creator Companion related issue to begin with. If you have any further questions about the creation process - i encourage you to check out official [VRChat Discord](https://discord.gg/vrchat) or the [Forums](https://ask.vrchat.com)
