### ISSUE TITLE
[BUG, URGENT] Unable to use Unity Version 2022.3.22f1 projects with VCC

### ISSUE THREAD

**Issue by luckydeerr** [vrchat-community/creator-companion#506]
### Describe the bug

Whenever I attempt to create, open, or change the version to Unity 2022.3.22f1 with VCC, it just opens the folder where the VCC executable is and gives me this error:

> "Unity path was not set, found it at C:\Program Files\Unity 2022.3.22f1\Editor\Unity.exe, saving to settings."

I have already tried reinstalling VCC several times, I've tried running VCC as an admin, and I have checked and verified that the Unity Path was set correctly in the VCC settings, and I've tried resetting the `settings.json` file to default settings, all of which don't resolve the issue.

Weirdly enough, I am able open 2022.3.22f1 projects perfectly fine through the Unity Hub itself.

Additionally, 2022.3.6f1 projects work just fine through VCC. I haven't tested other versions.

Below is the folder that opens whenever I try to use Unity version 2022.3.22f1 through VCC.

![image](https://github.com/user-attachments/assets/6c87ed6e-15ee-48b8-a6c3-4d3b919d6534)

### To Reproduce

1. Open VCC
2. Try to open or create a 2022.3.22f1 project, or try to change a project's version to 2023.22f1.

### Expected behavior

It opens or creates the 2022.3.22f1 project without issue.

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.3.2

### OS

Windows 11

**Comment by luckydeerr** [comment]
-SOLVED-

Just needed a fresh Unity/Unity Hub reinstall

**Comment by dudu08439-hash** [comment]
I'm having this issue and I don't know how to resolve it, I've tried uninstalling and reinstalling unity, vcc, and the hub nothing has worked

**Comment by xskutsu** [comment]
i'm having this issue as well
