### ISSUE TITLE
[BUG] Template name not using "displayname" from .json

### ISSUE THREAD

**Issue by VRCEtheri** [vrchat-community/creator-companion#51]
Template name not using "displayname" from .json

1. Copy a template into the templates folder
2. Name the directory "AFolderName" 
3. Edit package.json "displayName" property to a name different than the directory "A much cooler template" 
4. Open the creator companion 
5. Create new project 
Observe: Template is named after the directory <AFolderName> rather than the displayName property

![image](https://user-images.githubusercontent.com/113936841/208167497-6e01f870-168d-452f-8bfe-967e553ca434.png)

**Comment by orels1** [comment]
Addressed in the next release
