### ISSUE TITLE
[BUG] Latest SDK is still 3.6.1, not 3.7.0.

### ISSUE THREAD

**Issue by BluWizard10** [vrchat-community/creator-companion#520]
### Describe the bug

When creating a new project in Creator Companion v2.3.2 (Latest), on today's date, August 21, 2024, the automatically installed SDK is not 3.7.0. It's instead automatically assigning 3.6.1.

Is there some back-end code that needs to be updated?

### To Reproduce

1. Create a new Avatar 2022 Project in VCC v2.3.2.
2. Check which SDK version it installs. In my case, it used 3.6.1 instead of the latest 3.7.0 version.

### Expected behavior

The SDK that's installed by default on a New Project should always be the latest.

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.3.2

### OS

Windows 10

### Additional context

Build Info:

```
{
  "version": {
    "Major": 2,
    "Minor": 3,
    "Patch": 2,
    "PreRelease": null,
    "Build": null,
    "IsPreRelease": false
  },
  "branch": "main",
  "commit": "496eeec2ac35d319de2de3c4ab357e56e6f8f009",
  "portable": false
}
```

**Comment by orels1** [comment]
The templates are currently targeting 3.6.x SDK
We'll look into updating those
