### ISSUE TITLE
[FEATURE] [VCC-WEB]  Indicate when a project is opening / already open

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#53]
**Issue:**
In live, the `Open Project` button turns into a `Bring To Front` button if the project is already open. This made it easier to not accidentally try to open a project again and was a clear indicator if a project was already open.

**Suggestion:**
When pressing the `Open Project` button it should turn in to a none clickable `Loading` indicator. This would make it clear that you have already pressed the button to open the project and that you just have to wait for it to open. Once a project is fully opened the `Loading` indicator should turn into a `Bring To Front` button. This would as said before make it clear that the project is already open and would help to find it again on your desktop.

**Comment by momo-the-monster** [comment]
We've switched from using WatsonTCP for this connection to WebSockets, and will need to release an SDK build which implements the WebSocket connection logic in order to close this loop.

**Comment by orels1** [comment]
Addressed internally, part of closed beta 3
