### ISSUE TITLE
[BUG] Suddenly unable to access official / curated repository from github actions

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#542]
### Describe the bug

Suddenly unable to access official / curated repository from GitHub Actions environment.

This makes our CI broken.

https://github.com/anatawa12/AvatarOptimizer/actions/runs/11319160861/job/31474796084?pr=1257

### To Reproduce

1. Create GitHub Actions accessing `https://packages.vrchat.com/official?download` or `https://packages.vrchat.com/curated?download`
2. return 403

### Expected behavior

403 redirect to `https://vrchat.github.io/packages/index.json?download` should be returned

### Related Product

VCC (VRChat Creator Companion)

### Product Version

N/A

### OS

macOS / Linux

**Comment by anatawa12** [comment]
https://github.com/anatawa12/vcc-official-curated-repository-unaccessiable-from-github-actions-test/actions/runs/11319884155/job/31476592735

I found that `User-Agent` is related. with `User-Agent: vrc-get/1.8.1` fails

**Comment by anatawa12** [comment]
The response says product and version is reuqired but vrc-get is the product name and version is 1.8.1.

**Comment by anatawa12** [comment]
even with url to vrc-get repository as a contact, fails. https://github.com/anatawa12/vcc-official-curated-repository-unaccessiable-from-github-actions-test/actions/runs/11319937228/job/31476712621

**Comment by orels1** [comment]
Have you tried giving it an email address for contact info?

**Comment by anatawa12** [comment]
I added my email address but not working.

https://github.com/anatawa12/vcc-official-curated-repository-unaccessiable-from-github-actions-test/actions/runs/11323032426/job/31484869342#step:2:5

**Comment by bdunderscore** [comment]
On my side, I've worked around this by directly referencing the github.io VPM repo, but I'm not sure if that's meant to be a stable URL, so it'd be good to fix this issue.

**Comment by orels1** [comment]
@anatawa12 @bdunderscore 
you should be able to continue using `vrc-get/<version> (<contact information)` user-agent going forward
the main rule is providing contact information, otherwise it will get 403 response for non-compliance once more
