### ISSUE TITLE
[FEATURE] Suggest adding a batch package management function

### ISSUE THREAD

**Issue by AlanBacker** [vrchat-community/creator-companion#547]
**Is your feature request related to a problem? Please describe.**
Managing a project with many packages is too troublesome. Often, when dealing with a large number of updates or needing to add or delete packages in bulk, clicking one by one and waiting for each to load takes a considerable amount of time.

**Describe the solution you'd like**
I hope a batch management function can be added, allowing for searching packages by name, batch selecting packages, and performing add, delete, and update operations.  This should also include error prevention and warnings to the user when necessary, explaining potential conflicts from updating certain packages.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by orels1** [comment]
I think this is somewhat covered by
- #546 
- #172 
- #331 

feature requests

**Comment by AlanBacker** [comment]
> I think this is somewhat covered by
> 
> * [[FEATURE] Package Favorites #546](https://github.com/vrchat-community/creator-companion/issues/546)
> * [Update All Button #172](https://github.com/vrchat-community/creator-companion/issues/172)
> * [[FEATURE] Install packages in parallel or in FIFO order in the background. #331](https://github.com/vrchat-community/creator-companion/issues/331)
> 
> feature requests

i see, thank you for your hardworking!
