### ISSUE TITLE
[BUG] [VCC-Web] [Windows] VCC opens ghost explorer processes

### ISSUE THREAD

**Issue by hyblocker** [vrchat-community/creator-companion#55]
### Describe the bug
When a user goes to a project and clicks the "Open Project Folder" button, VCC spawns a new instance of `explorer.exe` on Windows. This is problematic as on Windows, `explorer.exe` acts as both the file manager and the taskbar. Due to this, any other instances of `explorer.exe` other than the once which also acts as the taskbar open as a new instance, and when the user closes it, the process remains loaded in memory as a ghost process, which becomes problematic for certain types of users.
The better solution on Windows is to use [SHOpenFolderAndSelectItems](https://learn.microsoft.com/en-us/windows/win32/api/shlobj_core/nf-shlobj_core-shopenfolderandselectitems), which opens a folder in the main `explorer.exe` process.

### To Reproduce
1. Observe the number of `explorer.exe` processes on Windows via Task Manager or something similar.
2. On VCC, select the "..." button on a project.
3. Click the "Open Project Folder" button.
4. Notice via Task Manager or something similar that another `explorer.exe` process is running.
5. Notice that closing the newly opened File Explorer window does not terminate the newly opened `explorer.exe` process, leaving it as a ghost process.

### Expected behavior
Viewing project files does not launch processes which tend to become ghost processes once seemingly closed.

### Screenshots
N/A

### Desktop
 - **OS:** Windows 11 Pro
 - **Version:** vcc_2.0.0-beta.1

### Additional context
The main reason this bugs me currently is due to the fact that on Windows, `explorer.exe` processes which don't act as the taskbar tend to be significantly more problematic for the average user. While I know that I can run `taskill /f /im explorer.exe && timeout 1 && explorer.exe` from command prompt to alleviate this, I don't expect the average user to be aware of how to do this, but instead notice odd behaviour. This is more problematic on laptops due to most people tending to sleep their machines, not giving them the opportunity to restart (killing the ghost processes in the process).

**Comment by momo-the-monster** [comment]
Fixed in next release of the VCC.
