### ISSUE TITLE
[BUG] Entire project gets laggy and flickery after uploading or removing something from project.

### ISSUE THREAD

**Issue by sofialia** [vrchat-community/creator-companion#57]
**Describe the bug**
(rewritten after discovering a lot more about said bug)
The behavior is hard to explain. The project gets laggy, flickers/reloads with almost every click, impossible to work on. This happens after uploading (most times but not all), as well as when removing something from the assets. Another side effect of this state: GestureManager claims that there are no active avatar descriptors in the hierarchy, even though there are. The issue can be temporarily fixed by opening VCC and removing GestureManager from the project and reimporting. I am not aware of any other fixes.

**To Reproduce**
Uploading an avatar.
or
Removing something from Assets.

**Expected behavior**
A non laggy and non flickering workable project.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: (not sure how to find this, please let me know)

**Comment by Faxmashine** [comment]
Thanks for the report! We're unable to reproduce this issue. Can you confirm that it still occurs with version 2.0.3 of the Creator Companion? Are there any other reproduction steps you would like us to try, i.e. creating a brand new project, performing a fresh install of Unity, etc?

**Comment by Faxmashine** [comment]
Closing this issue to inactivity and inability to reproduce it.

Please let us know if you see it again! Thank you for your report.
