### ISSUE TITLE
[BUG] Unable to share World SDK projects in git due to invalid References

### ISSUE THREAD

**Issue by EinDev** [vrchat-community/creator-companion#59]
**Describe the bug**
I am using git to share my unity project, but once i clone the project it breaks severely. References start breaking beacause things like "VRC_SceneDescriptor" are missing somehow.

**To Reproduce**
1. Setup a project on a repo using the .gitignore from here: https://thoughtbot.com/blog/how-to-git-with-unity
2. Clone the repo and open the cloned variant on unity
3. Confirm the package installation
4. See the errors. 

**Expected behavior**
I would expect the Package Manager to install the VRChat World SDK, which should include the proper VRC_SceneDescriptor.

**Screenshots**
![VRCHAT_CC_Error](https://user-images.githubusercontent.com/12981672/211411481-86207b79-9480-4fad-927d-44e1e9f4dfa3.PNG)
As you can see in the Screenshot, there are Entities missing in the Assembly, like the VRCSceneDescriptor. But at the same time, the Assembly version seems to be correct (if i right-click the file and view the version) and the version in the package manager also seems to be correct. Removing the files via VCC and adding them again does not help either.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 21H2

**Additional context**
If you have any ideas for a workaround, please tell me :) I don't know where the issue is and how to resolve it

**Comment by momo-the-monster** [comment]
@EinDev - two questions - 

1. Does pressing "Reload SDK" from the VRChat SDK menu in Unity fix the issue?
2. Can you try making a new git-backed UdonSharp project by using [this template and the included instructions](https://github.com/vrchat-community/template-udonsharp)?

**Comment by EinDev** [comment]
Thank you for the quick response.
1. Unfortunately it does not help.
2. Weirdly enough, if i clone the template repository it behaves exactly the same. If i open the "UdonExample" Scene from The world SDK, it does not even show the VRC_SceneDescriptor:
![grafik](https://user-images.githubusercontent.com/12981672/211675617-9c90de4e-1ebb-4ccb-94b1-54192e4a4089.png)
I didn't bother to try to set up my own repo with this template, as the issue is already present on the sample repo appearently.

I can confirm i am not the only one having this issue, a friend of me has exactly the same issue.

**Comment by momo-the-monster** [comment]
Hm - I just cloned the repo anew, and I did see the same issue you mention where some scripts do not fully load on first open, but in my case, running VRChat SDK > Reload SDK (and then refreshing assets using Ctrl-R) did fix it for me.

**Comment by EinDev** [comment]
CTRL+R did the trick, thank you. Do you have any idea why this error occurs in the first place?

**Comment by momo-the-monster** [comment]
Yes - Unity imports some parts of some packages in the incorrect order and then fails loading some required DLLs. It's a known issue for Unity 2019. Unity has fixed it in 2020+ but was not willing to backport the fix for us. The SDK has some logic to automatically reimport the DLL after the first load, but it doesn't work 100% of the time.
