### ISSUE TITLE
[FEEDBACK] [VCC-WEB] the Installed / Update Icon should be in front of the version number

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#61]
**Issue:**
Currently the check marks for a Package being Installed and for a Package needing an Update are put behind the version number. This results in them shifting left / right depending on the length of the version number. This is visually a bit unpleasing and makes it harder to quickly skim over your packages to see which one needs an update.

**Suggestion**  
Put the check marks in front of the version number. This would stop them from shifting left / right when the length of the version number changes and makes it easier to quickly see which packages need an update.

**Attachments:**  
Here is a picture showcasing the issue:
![image](https://user-images.githubusercontent.com/46327609/211879006-196555db-1ef7-4e45-86c9-da186f90e4c7.png)

**Comment by momo-the-monster** [comment]
Fixed in next release!
