### ISSUE TITLE
[FEEDBACK] [VCC-WEB] the Update buttons should be positioned behind the delete button

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#62]
**Issue:**
Currently the Update Package buttons is put in front of the Delete button. This results in the delete button being moved to the right, where it no longer is in lines up with the rest of the delete buttons from other packages. This b

**Suggestion**  
Put the Update button behind the Delete button, this would keep all the delete buttons in line and not move them around.

**Attachments:**  
Here is a picture showcasing the issue:
![image](https://user-images.githubusercontent.com/46327609/211883418-c0f51715-895d-4e55-b29b-719782eb8c63.png)

**Comment by momo-the-monster** [comment]
Fixed in next release!
