### ISSUE TITLE
[FEATURE / FEEDBACK] [VCC-WEB] Themes should be split up between using System, Dark and Light

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#63]
**Issue:**
Currently you can only choose between Dark and Light mode and there is no clear way to tell the program to always use the System Theme. I've been told that the System Theme still has an effect on, this makes the Theme selection a bit confusing / complicated in my opinion.

**Suggestion:**  
In the Themes drop down give the user 3 options to choose from:  
1. System: Always follow what ever Theme the operating system is set to  
2. Dark: Always use the Dark Theme  
3. Light: Always use the Light Theme
I think this would be the most optimal way to do the Themes selection as it's clear what each option does.

**Comment by momo-the-monster** [comment]
Fixed in next release!
