### ISSUE TITLE
[BUG] [VCC-WEB] Unity and VRChat appear as a part of the VCC in Task Manager

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#64]
**Issue:**
When the VCC opens Unity it will appear as part of the VCC in Task Manager. The same thing happens to VRChat when launching a local test client.

**Expected Behavior:**    
Unity and VRChat (local test clients) should show up as individual programs in Task Manager to better see the System usage of each application independently.

**Attachments:**  
Here is a picture showcasing the issue:
![image](https://user-images.githubusercontent.com/46327609/211887230-72fb27a9-fa76-4b54-9b7a-ca80c71ce1ed.png)

**Comment by momo-the-monster** [comment]
Fixed in next release.
