### ISSUE TITLE
[BUG] Incorrect Avatar/package.json downloaded via vpm on Linux

### ISSUE THREAD

**Issue by alertedsnake** [vrchat-community/creator-companion#69]
**Describe the bug**
When I use `vpm install templates` on Linux, the `VRCTemplates/Avatar/package.json` seems to be the one from the `Base` template instead:
```
{
        "name" : "com.vrchat.template.base",
        "displayName" : "Base VRChat Project",
        "description" : "",
        "version" : "1.0.0",
        "category" : "ProjectTemplate",
        "dependencies" : {}
}
```

**To Reproduce**
1. run `vpm install templates`
2. observe `VRCTemplates/Avatar/package.json` and `VRCTemplates/Base/package.json` are the same file

**Expected behavior**
I'm assuming this should be different since the one in my userdir on my Windows machine looks like this:
```
{
        "name" : "com.vrchat.template.avatar",
        "displayName" : "VRChat Avatar Project",
        "description" : "",
        "version" : "1.0.0",
        "category" : "ProjectTemplate",
        "dependencies" : {}
}
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.1.13

**Comment by momo-the-monster** [comment]
@alertedsnake - this should be fixed now, we pushed an update to the templates yesterday. You may need to run `vpm install templates` again to get the newest versions.
