### ISSUE TITLE
[FEATURE] an command to resolve dependencies of existing project

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#72]
**Is your feature request related to a problem? Please describe.**
I need to click 'OK' to resolve missing dependencies in unity project however, in CI / batch mode, we cannot click any dialog.

**Describe the solution you'd like**
Instead of using VPM Resolver, add vpm command to resolve dependencies of project like `vpm resolve`.

**Describe alternatives you've considered**
Use VPM Resolver but there're the following problems:
- VPM Resolver will not work in batch/headless mode. (described before)
- it is not good for running tests because it will cause compilation errors before resolving dependencies. With gameci, a popular ci running system, will report failure without running tests. because of the compilation error. 

**Additional context**
VPM Resolver's Error in batch mode:

![FmOyq53aMAEEuEO](https://user-images.githubusercontent.com/22656849/212044915-c094829e-c690-4e8f-b44f-cb9844425f4b.png)

[Here][test-project] is the test to compatibility with VPM Resolver & gameci,.
[This][failure-before-running-test] is failing test with forcely calling Resolver with [this file][failure-force-resolver].
[This][successful-with-shell-resolve] is successful test with manually resolving dependencies using [shell script][successful-shell].

[test-project]: https://github.com/anatawa12/VPMResolverAndGameCI

[successful-with-shell-resolve]: https://github.com/anatawa12/VPMResolverAndGameCI/actions/runs/3909561666
[successful-shell]: https://github.com/anatawa12/VPMResolverAndGameCI/blob/32ca957b1de7d505e36da6904a08043b1afa1481/resolve-manually.sh

[failure-before-running-test]: https://github.com/anatawa12/VPMResolverAndGameCI/actions/runs/3910146409/jobs/6681998862
[failure-force-resolver]: https://github.com/anatawa12/VPMResolverAndGameCI/blob/194d626a6c9433cbbc22264a79fd65d3be5f1c4c/Assets/ForceResolveInBatchMode/ForceResolveInBatchMode.cs

**Comment by momo-the-monster** [comment]
[vpm resolve project](https://vcc.docs.vrchat.com/vpm/cli#resolve-project) is now available in the CLI!
