### ISSUE TITLE
[QUESTION] Why is the `vpm-manifest.json` incorrectly configured?

### ISSUE THREAD

**Issue by foxscore** [vrchat-community/creator-companion#74]
Usually, you would list the wanted packages in the dependencies object, and the installed packages *(wanted and dependent)* in the locked object *(or a separate file)*.

But the VPM manifest appears to be storing the installed / managed packages in `locked`, and the wanted packages, INCLUDING THEIR DEPENDENCIES, in `locked`.

Is my understanding of it correct, and if so, what's the reasoning behind it?

**Comment by orels1** [comment]
There have been some changes in the way VPM manifest is managed over the past year, so I'll close this.

Overall the `dependencies` list should store top-level dependencies, defining which packages are wanted by the project

While `locked` should store wanted+dependent installed packages in `locked`. The `locked` is then used by the VPM resolver to validate the actual packages on disk against it and download any missing packages
