### ISSUE TITLE
[PACKAGE] Harmony (and possibly others) as separate packages

### ISSUE THREAD

**Issue by foxscore** [vrchat-community/creator-companion#75]
**Full Name of the Package**
`Nuget.Lib.Harmony`

**Information about the Author**
`VRChat` — *It's you guys! :)*

**Describe the errors or issues you're having in a VPM project**
I need Harmony in some of my packages. However, UdonSharp already includes Harmony! This is problematic as my packages are not dependent on the World's SDK, thus me having to ship it in its own package. BUT, since UdonSharp already has it, Unity throws errors if my stuff is imported into *(a lot of)* World projects.

**List the VRC SDKs and other Packages in the project**
*Not of relevance*

**Additional context**
This problem is not limited to Harmony. Other packages may depend on libraries that may or may not be imported by other packages *(aka. a conflict)*. This kind of thing is why package managers exist. Unless imported by a mandatory package *(`com.vrchat.base`)*, every DLL should be its own package (`lib.harmony`) or in a bundle (`lib.dotnet-framework.essentials`).

**Comment by rrazgriz** [comment]
Really would be good to have Harmony as a managed dependency, it's a powerful tool that's necessary to get the editor to do certain things, as demonstrated by UdonSharp.

I have a [tool](https://github.com/rrazgriz/RATS) that relies on Harmony, and have ended up with the compromise of providing a [package](https://github.com/rrazgriz/harmony-vpm) (not as a dependency, critically: rrazgriz/RATS#15) as well as a scripting define that's set based on the Harmony assembly being available. This allows users to provide Harmony in more ways than one, and the tool to behave properly if Harmony isn't present, but means I can't make it a one-click-install without worrying about breaking if other tools (including U#) have already provided it.

While having it as its own package would be ideal (ideally in dll form, so it's available as early as possible in compilation), it'd still be great with `com.vrchat.base` bundling it as a mandatory dependency, if there's reasons to steer away from having more individual packages.

**Comment by rrazgriz** [comment]
`com.vrchat.base` 3.4.0 bundles a Harmony dll, yay! This allows Harmony-dependent packages to depend on the base SDK, which should be available in all projects. 

![image](https://github.com/vrchat-community/creator-companion/assets/47901762/582816ee-5eb1-47c2-8a3a-e8bffe99704c)

I've updated RATS to handle this: https://github.com/rrazgriz/RATS/releases/tag/1.1.4
