### ISSUE TITLE
[BUG] Adding package does not remove legacyFolders

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#76]
**Describe the bug**
Adding package via `vpm add` or VCC (unity) does not remove legacyFolders

**To Reproduce**
For this steps, I'm using liltoon for example.
1. Create VRC Avatars project.
2. Download [liltoon] unitypackage and import to the project.
3. Download [liltoon] zip, extract and add as user Package.
4. Open the project with VCC
5. Add liltoon in VCC

[liltoon]: https://github.com/lilxyzw/lilToon/releases/latest

**Expected behavior**
`Assets/lilToon` folder should be removed according to `legacyFolders` in `package.json`

**Actual behavior**
`Assets/lilToon` folder will still be exists and made an error about file / assembly duplication.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2 OR macOS 13
 - Version: VCC 1.0.6 OR VPM CLI 0.1.13

**Additional context**

**Comment by momo-the-monster** [comment]
@anatawa12 - I believe this issue is a duplicate of #24, do you agree?

**Comment by anatawa12** [comment]
I agree. Sorry for duplication.
