### ISSUE TITLE
[BUG] VPM CLI documentation is outdated

### ISSUE THREAD

**Issue by bdunderscore** [vrchat-community/creator-companion#8]
**Describe the bug**
The [VPM CLI documentation](https://vcc.docs.vrchat.com/vpm/cli/#add-package) does not match actual behavior.

**To Reproduce**
1. Try to use `vpm add com.vrchat.worlds` as indicated in the "add package docs"
2. Turns out you need to use `vpm add package com.vrchat.worlds` 

**Expected behavior**
Docs should match the CLI :)

**Comment by momo-the-monster** [comment]
[Fixed now](https://vcc.docs.vrchat.com/vpm/cli/#add-package), thanks!
![image](https://user-images.githubusercontent.com/737888/191123173-1f4431bc-8b08-4de4-9fa6-a82ad7c8e748.png)
