### ISSUE TITLE
[FEATURE] file path to show in the projects

### ISSUE THREAD

**Issue by Midnight-NOW** [vrchat-community/creator-companion#81]
**Add file path to show where the project is before clicking it**
when open a file to see what file it is and where old to new projects named the same but in a new folder, if its the wrongs got to go back and do it

**Describe the solution you'd like**
add the file path to the projects name view.

**Describe alternatives you've considered**
make the VCC Work faster not .5 seconds to load a file path to open that is stored to open it.

**Additional context**
![vcc](https://user-images.githubusercontent.com/92552976/215610645-91f74521-b976-41f3-ac21-8dfd1edd0701.png)

**Comment by orels1** [comment]
This should be addressed in the VCC 2.0!
[Grab it from here](https://vrchat.com/download/vcc)
