### ISSUE TITLE
[BUG] Can't upload avatar

### ISSUE THREAD

**Issue by V355EL** [vrchat-community/creator-companion#85]
So any time I try to upload an avatar it will give me the errors in the screenshot
![2023-02-09](https://user-images.githubusercontent.com/124975026/218007704-9002f01d-572c-4a82-99b3-bb757f9c742a.png)
and I'm not sure what caused this I have tried different projects and avatars but none of them work. I am on windows 10

**Comment by momo-the-monster** [comment]
@V355EL - this repo is for reporting issue related to the Creator Companion. For help with your Avatar, [try our Discord](http://discord.gg/vrchat). 

FWIW, it looks like your Avatar has a missing script, you should either re-link it or remove that component entirely.
