### ISSUE TITLE
[BUG] Local UPM on-disk package not including certain files in world build if package exists outside the unity project

### ISSUE THREAD

**Issue by techanon** [vrchat-community/creator-companion#9]
**Describe the bug**

**To Reproduce**
1) Create a VPM package containing some image configured as a sprite.
2) Add VPM package via Unity Package Manager as a local/on-disk package. The package location is external to the Unity project being used.
3) Create VRC world scene and add a Canvas with a UI image.
4) Add the sprite image from the local package to the Image component.
5) Build & Test.
6) Image is missing.

**Expected behavior**
Image to be present in the scene's UI

**Screenshots**
https://streamable.com/07jg9n

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Worlds 3.1.7

**Comment by orels1** [comment]
Is this still an issue when using it as a user package in the VCC?
UPM might be doing something unexpected as it references those folders through direct paths instead of embedding the contents in your projects

**Comment by techanon** [comment]
Well, coming back to this, it does not appear to be an issue anymore. Unsure if there was some sort of user error on my end or not (much has changed internally to my asset since this was posted).  
It does load them in properly now. *shrug*
I'll just mark as closed since it resolved itself.
