### ISSUE TITLE
[BUG] User-created folders may get deleted during migration.

### ISSUE THREAD

**Issue by momo-the-monster** [vrchat-community/creator-companion#91]
If a user creates a folder such as `Assets/MyCoolPrefab/Udon`, the `Udon` folder will get deleted.

This is a regression. The Unity VCC leaves that folder untouched when migrating.

Other folder names may be affected, too. (i.e. VRCSDK)

**Comment by orels1** [comment]
Fixed internally, part of closed beta 3
