### ISSUE TITLE
[BUG](problem in Official Repository) cache-control max-age is too long

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#93]
**Describe the bug**
Because `max-age` of `cache-control` is too big, I cannot see VRCSDK 3.1.11 in vpm official repository.

**To Reproduce**

With vpm CLI
1. Execute `vpm list repo 'https://packages.vrchat.com/official?download'`
2. VRCSDKs version 3.1.11 should be listed in versions but not

With curl
1. Execute `curl -vL 'https://packages.vrchat.com/official?download'`
2. VRCSDKs version 3.1.11 should be listed in versions but not

**Expected behavior**
`https://packages.vrchat.com/official?download` should return VRCSDK 3.1.11.

**Screenshots**
<img width="793" alt="image" src="https://user-images.githubusercontent.com/22656849/220820361-716a3bfa-66fa-4746-8679-6f2abc3d8a4c.png">

**Desktop (please complete the following information):**
tested on both macOS and windows

**Additional context**

According to curl's verbose output, the `max-age` of VPM Official repository is 1209600 seconds, which is 14 days.
For changeable resources like VPM repository, I think it's very too long.
If it's shorter (like one day, 86400 seconds), I'll wait for cache purge but I think it's too long so I made issue.
In the CDN Edge for me, Age of the resource is 145602 so I need to wait for 1063998 seconds, about 12 days.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/22656849/220821592-ef041cf2-6e6d-4ff3-af29-4da914f683f6.png">

I could not found the place for VPM Repositories so I opened the issue here. If you have some other better place, Could you notice me?

**Comment by momo-the-monster** [comment]
Unfortunately, our upstream provider was not willing to lower this value. So we've moved the listings to a new endpoint where we serve them with much better values!
