### ISSUE TITLE
[BUG] [VCC-WEB] VCC shows "Update Package" button, even though the version you have installed is newer

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#95]
**Issue:**  
When you manually update a Package to a version which is newer than what the VCC shows, an `Update` button will appear. Pressing this button will downgrade the package to what ever the VCC thinks is the latest version.

**Expected Behavior:**
Only show the update button when ever the VCC actually has a newer version available for a Package and not just when there is a mismatch between the installed and what ever the VCC thinks the latest version is.

**Attachments:**  
Here is a picture showcasing the issue:
![image](https://user-images.githubusercontent.com/46327609/220946749-81456970-37ee-42aa-ba5b-01a57584939b.png)

**Comment by orels1** [comment]
Addressed internally, part of closed beta 3
