### ISSUE TITLE
[BUG] [VCC-WEB] You can change the window size to be so small that the VCC is unusable

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#96]
**Issue:**  
It's possible for you to make the VCC window so tiny that basically only the minimize, maximize and close button are visible.

**Expected Behavior:**
Add a minimum window size to the VCC so that it is limited to a size that is still usable.

**Attachments:**  
Here is a picture showcasing the issue:
![image](https://user-images.githubusercontent.com/46327609/220948586-39b63eb7-6355-4a6c-86dd-d843764d2c07.png)

**Comment by orels1** [comment]
The window size has been capped to a reasonable minimum in the next closed beta release
