### ISSUE TITLE
[FEATURE] [VCC-WEB] top options bar in the Manage Project page should always be on top

### ISSUE THREAD

**Issue by DrBlackRat** [vrchat-community/creator-companion#97]
**Issue:**  
Right now you lose access to the top options bar of the Manage Project page when you scroll down a long list of packages. This means that to refresh the packages etc. you first need to scroll up again.
This is also different from how the Projects page behaves, as there the top options bar is always at the top of the window.

**Suggestion:**
The Manage Project page should behave similar to the Projects page, so that options bar is always visible at the top. Basically only make the packages them self scrollable instead of the entire page.

**Attachments:**  
Here are pictures showcasing the difference between Projects and Manage Projects:
![image](https://user-images.githubusercontent.com/46327609/220952579-8e8b7b9f-2830-43db-96b1-817bb11d05cd.png)
![image](https://user-images.githubusercontent.com/46327609/220952916-deaf8bc7-99c6-4845-bb2e-ecf3933f71c5.png)

**Comment by Faxmashine** [comment]
This has been fixed! 🎉
